cp2k/dbcsr

- src/acc/libsmm_acc/libcusmm/libcusmm_benchmark.cu
- src/acc/libsmm_acc/libcusmm/tune.py
The addition of macros related to hashing variables (commit 90c053640f49a2b85feadc6aa6ef58d7d53f7659) requires the automatically-generated Makefile in the auto-tuning facilities to define these variables as well
> Adapt autotuning to hashing macro variables

- Makefile
- Makefile.inc
- src/acc/libsmm_acc/libcusmm/generate_parameters.py
- src/acc/libsmm_acc/libcusmm/parameters_K20X.txt
- src/acc/libsmm_acc/libcusmm/parameters_K40.txt
- src/acc/libsmm_acc/libcusmm/parameters_K80.txt
- src/acc/libsmm_acc/libcusmm/tune.py
- Specify GPU version (i.e. K20, P100, ...) instead of ARCH_NUMBER in Makefile.inc
- Determine ARCH_NUMBER from GPUVER
- libcusmm/generate_parameters.py: read the correct parameter file depending on ARCH_NUMBER
- libcusmm/tune.py: choose compilation options (-arch sm_xx) depending on ARCH_NUMBER and cleanup macros rendered obsolete by new hash
> libcusmm: specify GPU version 

- src/acc/libsmm_acc/libcusmm/libcusmm_benchmark.cu
This non-ascii character prevented the file from being read when running `makedep.py` with Python 3 instead of Python 2.
> libcusmm: remove non-ascii character

- src/base/dbcsr_base_uses.f90
Allow DBCSR_ASSERT to be elided if NDEBUG is defined. Introduced TO_VERSION macro.
> DBCSR_ASSERT to be elided (NDEBUG). Introduced TO_VERSION macro.

- src/base/dbcsr_base_uses.f90
- src/utils/dbcsr_toollib.F
Call libxsmm_hash to implement joaat_hash. This function produces CRC32 hashes and leverages specific CPU instructions. The CRC32 hash may also improve the hash quality and distribution. LIBXSMM provides this function since v1.9.0-6 as part of the Fortran interface (tested in CP2K/intel fork since then). LIBXSMM v.1.10 will be the first release with the Fortran interface for libxsmm_hash.
> Joaat hash to produce CRC32 hashes

- src/acc/libsmm_acc/libcusmm/parameters_K20X.json
- Removes 9 autotuned parameter sets for the K20X which should not be run in libcusmm
- Closes #75
> libcusmm: remove parameter sets with m,n,k > 80

- .travis.yml
- CMakeLists.txt
- src/CMakeLists.txt
- src/base/dbcsr_base_uses.f90
- src/block/dbcsr_block_operations.F
- src/block/dbcsr_block_operations.f90
- src/data/dbcsr.fypp
* Functionality becomes available with LIBXSMM v1.10 although the actual interface was there forever. The version barrier was necessary because of portability issues with C_LOC (worked around with libxsmm_ptr1 and libxsmm_ptr2). 
* If LIBXSMM is not used (or because of insufficient version), MKL's omatcopy and imatcopy functions are used (this could be ported to OpenBLAS as well). Note that mkl_trans.fi is not used as the header is obolescent; use an implicit "interface" instead (link-time).
* CMake infrastructure is extended to add __MKL to the list of preprocessor symbols (depends on BLA_VENDOR or list of BLAS_LIBRARIES); this check is done in a backward compatible fashion (older CMake).
> Use LIBXSMM (or MKL) for out-of-place and in-place transpose (block-ops).

- Makefile
For building CP2K, VERSION is a command argument to make. This overrides
the VERSION variable set in DBCSR makefile if DBCSR makefile is invoked
by CP2K makefile.
> Avoid VERSION variable in DBCSR makefile for inclusion into CP2K.

- .travis.yml
- examples/dbcsr_example_3.cpp
- src/dbcsr.h
Following the discussion on #65 and in consideration of PR #64 which
adds a fully OO C++ interface, I consider it to be safer to drop the
aliased C++ functions for now to avoid that people start relying on an
interface we are going to change later on.
fixes: #65
> dbcsr.h: make functions static, drop C++ aliases

- src/base/dbcsr_base_uses.f90
Including libxsmm_config.h only works with LIBXSMM v1.8.2 and later. Otherwise, older versions of LIBXSMM still work if this header is not included (prior to v1.8.2 the header was not suitable for Fortran).
> Require LIBXSMM v1.8.2 or later

- src/block/dbcsr_block_operations.F
- src/block/dbcsr_block_operations.f90
Implemented partial copy/transpose ops using libxsmm_matcopy and libxsmm_otrans. Implementations will become effective post-v1.10 (another pointer-utility needed in LIBXSMM's F-interface). Attributed dst_tr/src_tr with INTENT(IN). Prettified code.
> Implemented partial copy/transpose ops using libxsmm.

- Makefile
The proposed changes make sure that we do not recompile all modules using a.F if a.F has changed, recompilation only happens if a.mod has changed (gfortran does not update a .mod file if it does not change).
For more information: http://lagrange.mechse.illinois.edu/f90_mod_deps/
CP2K Makefile solves this in the same way.
Needed for cp2k/cp2k#86, in order to to recompile cp2k only if dbcsr_api.mod has changed.
> Makefile change s.t. mod files are not recompiled unnecessarily

- src/data/dbcsr_data_methods.F
Removed padded data (over-allocation) for MATMUL, BLAS, and LIBXSMM code path. The SMM-layer is supposed to never cause OOBs (unless padding is clearly specified/determined). Previously, the +10-pad was cumbersome.
> Removed padded data

- CMakeLists.txt
> cmake: filter CUDA from required MPI components

- src/utils/dbcsr_toollib.F
> utils/dbcsr_toollib: follow USE/ONLY convention

- src/acc/libsmm_acc/libcusmm/notebooks/README.md
- src/acc/libsmm_acc/libcusmm/notebooks/requirements.txt
- Update PyYAML version requirement to resolve security vulnerability
- Specify that notebooks require py3, just like the autotuning and predicting scripts
> libcusmm/notebooks: update requirements

- tests/CMakeLists.txt
- tests/Makefile.inc
- tests/dbcsr_unittest3.F
Fixes to the building of tests
**cmake** 
- add `dbcsr_unittest3` to the DBCSR tests (really should have been done in PR #132 , where I updated the `Makefile` but forgot about `cmake` ... )
- add the generation of `libcusmm_unittest_multiply.cu` and `libcusmm_timer_multiply.cu` (really should have been done in PR #137 , but I again forgot about `cmake` ...)
**Makefile**
- add forgotten dependency on the template
> Fix build tests

- src/acc/libsmm_acc/libcusmm/README.md
- src/acc/libsmm_acc/libcusmm/predict.md
- src/acc/libsmm_acc/libcusmm/tune.md
Move the instructions for autotuning libcusmm cuda kernels from cp2k.org to github repo for a better separation of cp2k and dbcsr's documentation.
> libcusmm/tune: add autotuning procedure from cp2k.org

- src/block/dbcsr_block_operations.f90
Some of the block-ops cannot be used right away with LIBXSMM due to memory layout; these are reverted. The existing conditional compilation (checks for libxsmm beyond 1.10), would trigger the incorrect code once a new version of libxsmm is released. The blocks-ops that remain with libxsmm are thoughly tested. The format changes in dbcsr_block_operations.f90 are based on latest prettify (triggered with `make pretty`).
> Reverted incorrect block-op implementations

- src/data/dbcsr.fypp
- src/mm/dbcsr_mm_hostdrv.F
- src/mm/dbcsr_mm_hostdrv.f90
Alternative code-path using LIBXSMM's explicit batch interface (hosted by xsmm_process_mm_batch routine). Modernized the original integration with LIBXSMM (xsmm_process_mm_stack routine). For the latter, e.g. conditions are adjusted by likelihood of taking the IF-branch. The explicit batch interface internalizes the loop which processes a stack of matrices (this enables future tuning without touching the integration). The explicit batch interface is used if the LIBXSMM version is sufficient (upcoming v1.11).
> Modernized original LIBXSMM integration and use explicit batch interface

- src/tas/dbcsr_tas_mm.F
- src/tensors/dbcsr_tensor.F
This fixes compilation errors saying that the initialization used is not applicable to the object (IFORT 18.0.5).
> Adjusted way to nullify output-pointers (IFORT)

- src/core/dbcsr_lib.F
- src/core/dbcsr_timings.F
- src/mm/dbcsr_mm_hostdrv.F
Accommodate DBCSRv2 initialization flow:
* Moved libxsmm_init/libxsmm_finalize into dbcsr_init_lib_pre and dbcsr_finalize_lib respectively.
* init flow would fail as the timer facility is used before LIBXSMM is initialized;  
Note: CP2K's timer hook may be based on LIBXSMM.
* LIBXSMM init-flow should not be limited to MM/host (dbcsr_mm_hostdrv_lib_init).
* Up-lifting the initialization location is self-contained and fwd./bwd. compatible.
This change may complement PR #171.
> Accommodate DBCSRv2 initialization flow

- src/core/dbcsr_lib.F
- src/core/dbcsr_timings.F
Fixed crash in dbcsr_finalize_lib when initialized per dbcsr_init_lib_hooks (tested with CP2K+PR330). The root cause of the issue was following flow (stacktrace):
> dbcsr_finalize_lib  
dbcsr_print_timers  
timings_report_print  
collect_reports_from_ranks  
-> "timer_env => get_timer_env()".
In get_timer_env, "timer_env => list_peek(timers_stack)" fails due to the "timers_stack" not being setup/allocated. The only function that does that i.e., initializing an internal private SAVE variable is "add_timer_env".
PR #171 seems to intent to explicitly omit add_timer_env in case of a hook-based initialization (dbcsr_init_lib_hooks), likely assuming this is controlled externally. This leaves the conclusion that "dbcsr_print_timers" can only be called in dbcsr_finalize_lib in case of the …
> Fixed dbcsr_finalize_lib when initialized per dbcsr_finalize_lib

- Makefile
- Makefile.inc
Remove the superfluous variable `CXXOMPFLAGS`, and instead, add OpenMP flags to the variable `CXXFLAGS` directly.
This simplifies the Makefile and reduces the risk of issues such as https://github.com/cp2k/cp2k/issues/338 occurring.
> Makefile: remove superfluous variable CXXOMPFLAGS

- src/acc/dbcsr_acc_hostmem.F
Occurs when running tests/dbcsr_tensor_unittest built with MPI, OpenMP and CUDA support.
Credit goes to Joost VandeVondele @vondele
> Workaround race condition on ORNL's Summit

- src/acc/libsmm_acc/include/libsmm_acc.h
- src/acc/libsmm_acc/libcusmm/libcusmm.cpp
- src/core/dbcsr_lib.F
In DBCSR's initialisation, if DBCSR is compiled with OpenMP support, add a call checking whether libcusmm was compiled with OpenMP support as well.
See [discussion](https://github.com/cp2k/cp2k/issues/338) in CP2K for the need behind such a check.
Fixes #180
> Check the consistency between dbcsr and libcusmm when building with openmp

- src/mpi/dbcsr_mpiwrap.F
Rely on `mpi_comm_set_errhandler` instead of `mpi_errhandler_set`. The conditional compilation checks for MPIv3 (`__MPI_VERSION`) which is reasonable but may be not exactly related. This so far fixes linker errors with OpenMPI 4.x (see [here](https://www.open-mpi.org/faq/?category=mpi-removed) for a list of removed [legacy] functions). It is reasonable to assume that MPI function names are standardized since MPIv3 (portable ABI between different implementations of MPI). In addition, this changes also fixes source code comments (typos).
> Rely on mpi_comm_set_errhandler instead of mpi_errhandler_set

- CMakeLists.txt
- README.md
- cmake/CheckCompilerSupport.cmake
- cmake/compiler-tests/f2008-block_construct.f90
- cmake/compiler-tests/f2008-contiguous.f90
- cmake/compiler-tests/f2008-norm2.f90
- src/CMakeLists.txt
based on the discussion in #129, https://github.com/cp2k/cp2k/issues/142 and the fact that PR https://github.com/cp2k/cp2k/pull/158 was merged for CP2K this PR adds a check for F2008's `norm2` support in the compiler when using CMake.
> switch to F2008

- .travis.yml
fixes build on Travis/macOS
upstream "bug report" here:
https://travis-ci.community/t/issue-brew-formula-installation-fails-due-to-being-outdated/3872
> travis: update and cache homebrew

- src/block/dbcsr_block_operations.f90
Fixed OOB also in case of non-zero sized array (insufficient array size, no actual request to copy a block aka requested copy-size is nrows==0 or ncols==0). The previously proposed check was insufficient, and this PR just does the check similar to the loop-based implementation.
> Fixed OOB also in case of non-zero sized array

- src/acc/libsmm_acc/include/libsmm_acc.h
- src/dbcsr.h
Adjusted C-API to rely on void-signature in case where no functions-argument is expected (C++ would ask for an ellipsis whereas C implicitly uses an ellipsis if the signature is non-void but empty).
> C-API to use void-signature for no-arg functions

- src/mpi/dbcsr_mpiwrap.F
**Introduced mp_get_processor_name**  
This may be used to introduce the notion of a node. The simplest use would be to count the number of nodes as opposed to the number of ranks. The node-count may help to recommend/hint better MPI/OpenMP decomposition. The latter can complement https://github.com/cp2k/cp2k/tree/master/tools/plan_mpi_omp.
**Misc**
* Fixed routine names mentioned in error messages.
* Some code cleanup (len->LEN).
> mpiwrap: mp_get_processor_name and cleanup

- src/mm/dbcsr_mm_hostdrv.f90
A user of the DBCSR-library can chose to define DBCSR_LIBXSMM_GEMM_BATCH as `libxsmm_gemm_batch_omp`, and additionally link against libxsmmext (on top of libxsmm and libxsmmf). This change allows to speedup the runtime when relying on POPT-builds (e.g., CP2K).
The symbol DBCSR_LIBXSMM_GEMM_BATCH allows to switch from between `libxsmm_gemm_batch` to `libxsmm_gemm_batch_omp`. This is a minimal change with no complementary adjustment of the build systems; it does not introduce potentially complicated build-logic (Make and CMake).
Note: `libxsmm_gemm_batch_omp` safely operates on a batch of SMMs even if there are duplicated C-indexes (synchronization).
> Potentially accelerate MPI-only operation by using OpenMP based libxsmm_gemm_batch

- src/mm/dbcsr_mm.F
Previously version checks failed with internal errors when the
patch-component contained additional components, which is often the case
for packages provided by Linux distributions.
Example from OpenSUSE:
Open MPI v3.0.0.0.1cbdf5d279, ...
> mm: fix RMA detection for distro-provided OpenMPI

- src/acc/include/acc.h
Introduced typedefs for void* (acc_stream_t, acc_event_t). Ensure void-signatures in cases where no argument is expected. Added ACC interface bits (acc_clear_errors, acc_dev_mem_set_ptr). Turned C++-style comments into C-style comments (C89 compatibility). This change is related to issue #212.
> ACC interface cleanup

- src/tas/dbcsr_tas_base.F
- src/tas/dbcsr_tas_global.F
- src/tas/dbcsr_tas_io.F
- src/tas/dbcsr_tas_mm.F
- src/tas/dbcsr_tas_reshape_ops.F
- src/tas/dbcsr_tas_split.F
- src/tas/dbcsr_tas_types.F
- src/tensors/dbcsr_tensor.F
- src/tensors/dbcsr_tensor_api.F
- src/tensors/dbcsr_tensor_block.F
- src/tensors/dbcsr_tensor_index.F
- src/tensors/dbcsr_tensor_io.F
- src/tensors/dbcsr_tensor_reshape.F
- src/tensors/dbcsr_tensor_split.F
- src/tensors/dbcsr_tensor_test.F
- src/tensors/dbcsr_tensor_types.F
- tests/dbcsr_tas_unittest.F
- tests/dbcsr_tensor_unittest.F
With these changes, process grids and process sub-groups are optimized internally in tensor contraction based on estimated sparsity of result tensor. Subsequent tensor contractions with tensors of similar shape and sparsity can optionally reuse optimized grid.
Finally (with corresponding changes in CP2K, a pull request will follow), we can get rid of the performance-critical parameters [GROUP_SIZE_3C](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT/XC/WF_CORRELATION/IM_TIME.html#GROUP_SIZE_3C) and [GROUP_SIZE_P](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT/XC/WF_CORRELATION/IM_TIME.html#GROUP_SIZE_P) in CP2K.
This pr comes with some API changes, probably the last tensor API changes before v2.0.
> Tensors: better heuristics for parameters affecting parallelism

- src/core/dbcsr_config.F
- src/data/dbcsr_mem_methods.F
- src/mm/dbcsr_mm.F
This circumvents the following issues #242:
1) memory may be needed otherwise
2) large memory pools cause inefficiencies for small matrix
multiplications
Issue 2) should be properly fixed but the presence of this configuration
option will still be justified by 1).
> Disable mempools on CPUs by default

- src/acc/dbcsr_acc_devmem.F
- src/acc/include/acc.h
- src/acc/libsmm_acc/include/libsmm_acc.h
- src/tensors/dbcsr_tensor_block.F
Fixed compilation with xlf (dbcsr_tensor_block.F). Fixed typos (dbcsr_acc_devmem.F). ACC/SMM/interface: include guards, rely on acc_stream_t (rather than void*), and code cleanup.
> Various (smaller) fixes

- tools/build_utils/makedep.py
A "circular dependency" such as "module -> module" is dropped. The latter can appear for PACKAGE files that contribute to the same archive (libdbcsr), which is just fine.
The change will be also proposed for CP2K's copy of makedep.
> Adjusted makedep to drop self-dependencies

- .ci/daint.cscs.ch/Jenkinsfile
Documentation about the setup can be found here: https://github.com/cp2k/dbcsr/wiki/CI-Setup#jenkins--cscs
> ci/daint: use Swift's S3 API to share build & test logs on publicly available space

- CMakeLists.txt
- Makefile
- src/CMakeLists.txt
- src/acc/PACKAGE
- src/acc/acc_event.cpp
- src/acc/acc_init.cpp
- src/acc/acc_stream.cpp
- src/acc/cublaswrap/PACKAGE
- src/acc/hipblaswrap/PACKAGE
- src/acc/include/PACKAGE
- src/acc/include/acc.h
- src/acc/include/acc_libsmm.h
- src/acc/libsmm_acc/PACKAGE
- src/acc/libsmm_acc/include/PACKAGE
- src/acc/libsmm_acc/libsmm_acc.cpp
- src/acc/libsmm_acc/libsmm_acc.h
- src/acc/libsmm_acc/libsmm_acc_benchmark.h
- src/acc/libsmm_acc/libsmm_acc_init.cpp
Regain separate implementations for ACC ("cuda", "hip", later "openmp") and ACC_LIBSMM ("libsmm_acc", later "libsmm_omp"). This change also includes the updated interfaces (header files) for ACC and ACC_LIBSMM both implementing improved type-safety. Both, CUDA and HIP backends are updated accordingly.
In addition, the CUDA/HIP backend got some minor adjustment to pass with the new/upcoming ACC/interface test (`acc_stream_destroy`, `acc_event_destroy`). Also, some issue compiling with CUDA on POWER received an update (disabled "issue seems to be present even with CMake 3.14.5 in some environments" as it is present with newer CMake).
> Separate implementations for ACC and ACC_LIBSMM

- src/acc/acc_mem.cpp
The function `acc_memcpy_d2h` was using `MemcpyHostToDevice` instead of `MemcpyDeviceToHost`.
This fixes #271.
Thank you, @hfp !
> acc_mem: fix wrong enumerator in acc_memcpy_d2h

- src/tensors/dbcsr_tensor.F
- src/tensors/dbcsr_tensor_types.F
API change: Tensor dimensions as optional argument to dbcsr_t_pgrid_create.
> Tensors: better defaults for automatic choice of process grid dimensions

- src/acc/libsmm_acc/libsmm_acc.cpp
- src/acc/libsmm_acc/libsmm_acc.h
- tests/dbcsr_unittest3.F
- **libsmm_acc**: fix a concurrency bug
The static variable `cpu_fallback`, once set to `false` by one
thread, was causing other threads to fall back to the CPU although
they could launch a kernel on the GPU.
Solve this issue by determining whether to fall back to the CPU
using the state of the "kernel handle", and getting rid of the static
variable `cpu_fallback`.
Also introduce a typedef and some simplifications for readability.
- **libsmm_acc**: remove superfluous ifdefs around openmp pragmas
- **tests**: add very small and very large block sizes
> libsmm_acc: bugfix

- Makefile
If compiling with nvcc, automatically add `-D__CUDA` to `NVFLAGS` in the `Makefile`.
This removes the need to add `-D__CUDA` to CP2K arch files when compiling CP2K with DBCSR > v2.0.1. 
Solves the issue in https://github.com/cp2k/cp2k/pull/744 .
> make: add -D__CUDA if compiling with nvcc

- .ci/daint.cscs.ch/Jenkinsfile
- src/tas/dbcsr_tas_base.F
- src/tensors/dbcsr_tensor_types.F
With this workaround, `dbcsr_tensor_unittest` should run with Cray CCE compiler. Unfortunately I'm still not sure whether this is a bug on our side or a bug in the compiler.
For documentation, some details on the issue:
Output and gdb backtrace (commit 9139540254f55a37022f0c0d08bfc563bb4b71e8, compiler flags `-G0 -O0 -g -Rb`):
```
lib-4961 : WARNING 
Subscript 69360416 is out of range for dimension 1 for array
'list' at line 68 in file 'dbcsr_array_list_methods.F' with bounds 1:14.
Program received signal SIGSEGV, Segmentation fault.
0x00000000007c897b in get_array_elements (get_array_elements=..., list=..., 
indices=...) at tensors/dbcsr_array_list_methods.F:68
68               get_array_elements(i) = list%col_data(ind)
(gdb) bt
#0  0x00000000007c897b in get_array_elements …
```
> workaround for CCE compiler

- cmake/CompilerConfiguration.cmake
- src/CMakeLists.txt
- src/core/dbcsr_lib.F
- tests/dbcsr_performance_driver.F
- tests/dbcsr_performance_multiply.F
- tests/dbcsr_test_multiply.F
DBCSR source code should respect the 132 character limit (as specified
in the Fortran standard).
Use only filename for __SHORT_FILE__ (as in CP2K) to avoid exceeding the
line length.
> CMake: use default '-ffree-line-length' of 132 for gfortran

- src/tas/dbcsr_tas_mm.F
- src/tensors/dbcsr_tensor.F
- src/tensors/dbcsr_tensor_api.F
This generalizes `retain_sparsity` feature of DBCSR matmul to tensors. A new API routine is made available to predict sparsity pattern of contraction result.
> Tensors: new features for `dbcsr_t_contract`

- src/tensors/dbcsr_array_list_methods.F
- src/tensors/dbcsr_tensor.F
- src/tensors/dbcsr_tensor_api.F
- src/tensors/dbcsr_tensor_block.F
- src/tensors/dbcsr_tensor_index.F
- src/tensors/dbcsr_tensor_io.F
- src/tensors/dbcsr_tensor_split.F
- src/tensors/dbcsr_tensor_test.F
- src/tensors/dbcsr_tensor_types.F
- tests/dbcsr_tensor_unittest.F
intent(out) allocatables cause problems with C interoperability.
- allocations of arrays with known sizes should be controlled by the caller
- helper functions to get array sizes
- `dbcsr_t_contract_index` is the only exception, array size is not known
prior to calling this function
This helps with finalizing #274
> Tensors: avoid use of intent(out) allocatables at the API level

- src/dist/dbcsr_dist_util.F
The temporary array is issued here: [https://github.com/cp2k/dbcsr/blob/develop/src/mm/dbcsr_mm_cannon.F#L1066](https://github.com/cp2k/dbcsr/blob/develop/src/mm/dbcsr_mm_cannon.F#L1066).
> avoid array-temporary

- src/data/dbcsr_ptr_util.f90
Removed OpenMP critical section around mp_allocate since it calls MPI_TYPE_SIZE() and MPI_Mem_alloc() both of which are thread-safe (contribution suggested by Dmitri M.).
> removed OpenMP critical section around mp_allocate

- src/mm/dbcsr_mm_cannon.F
- src/mm/dbcsr_mm_common.f90
In calc_norms, ABS was removed and a simd-loop was introduced. In addition, the `schedule(dynamic)` was specified (which is default with GNU Compiler), however the loop in particular is potentially unbalanced due to data-dependent `DATA(bp:bpe)`.
> revised calc_norms

- src/tas/dbcsr_tas_test.F
- src/tensors/dbcsr_tensor_test.F
- tests/dbcsr_tensor_unittest.F
Behaviour of these unit tests was inconsistent with different compilers and with different parallelization parameters due to use of `random_number` and list-directed IO.
This may also fix the failures of TAS unit test with Cray CCE compiler.
> TAS/tensor unit tests: consistent behaviour for different compilers and parallelization parameters

- src/tensors/dbcsr_tensor.F
- src/tensors/dbcsr_tensor_api.F
- src/tensors/dbcsr_tensor_index.F
- src/tensors/dbcsr_tensor_types.F
This is a follow-up to #320 according to what was discussed in #274
> Tensors: use static array size for `dbcsr_t_contract_index`

- .ci/daint.cscs.ch/cray.test.sh
- .ci/daint.cscs.ch/gnu.test.sh
- .ci/daint.cscs.ch/intel.test.sh
- src/tas/dbcsr_tas_global.F
- src/tas/dbcsr_tas_io.F
- src/tas/dbcsr_tas_mm.F
- src/tas/dbcsr_tas_test.F
- src/tensors/dbcsr_tensor.F
- src/tensors/dbcsr_tensor_api.F
- src/tensors/dbcsr_tensor_io.F
- src/tensors/dbcsr_tensor_test.F
- src/tensors/dbcsr_tensor_types.F
- tests/dbcsr_tas_unittest.F
- tests/dbcsr_tensor_unittest.F
This pr introduces an improved default distribution for tensors for internal and external use (new API function `dbcsr_t_default_distvec`). The algorithm is competitive with `make_basic_distribution` in CP2K (tested with `H2O-dft-ls.inp` benchmark).
The tensor API now departs from the design decision of DBCSR to leave the distribution up to the user. IMO it would be very useful to provide a default distribution in the DBCSR API and not just for tensors.
> Tensors: improved load balancing

- src/tas/dbcsr_tas_base.F
- src/tas/dbcsr_tas_io.F
- src/tas/dbcsr_tas_reshape_ops.F
- src/tas/dbcsr_tas_split.F
- src/tas/dbcsr_tas_test.F
- src/tensors/dbcsr_tensor.F
- src/tensors/dbcsr_tensor_block.F
- src/tensors/dbcsr_tensor_types.F
implicit save variables are shared and thus not thread-safe
This fixes #344
> Tensors/TAS: remove `=> NULL()` pointer initializations

- src/CMakeLists.txt
- src/acc/dbcsr_acc_device.F
- src/acc/dbcsr_acc_devmem.F
- src/acc/dbcsr_acc_event.F
- src/acc/dbcsr_acc_init.F
- src/acc/dbcsr_acc_stream.F
- src/acc/dbcsr_acc_timings.F
- src/acc/libsmm_acc/libsmm_acc.cpp
- src/acc/libsmm_acc/libsmm_acc.h
- src/core/dbcsr_timings.F
Now `jit_kernel_multiply` and `jit_kernel_transpose` appear in DBCSR's timing section, presenting information on the JIT overhead and helping to diagnose possible performance issues.
> Feature: call `timeset` inside libsmm acc

- src/block/dbcsr_block_access.F
- src/block/dbcsr_iterator_operations.F
Rely on OpenMP atomic when writing matrix%valid property. Reduced code in "crit_common_pos" critical section.
> minor tweaks for some OpenMP synchronization

- src/tas/dbcsr_tas_split.F
- src/tensors/dbcsr_tensor_api.F
The optimizations introduced in a7ab9d7a64f2e98624bb3c57a86dcb3ee842b54d
led to often non-square process grids, causing an overhead in memory
usage.
Unrelated: make tensor routines for output public.
> TAS: minor tweak ensuring square DBCSR grids

- src/tensors/dbcsr_tensor_api_c.F
When compiling DBCSR on Mac OS 10.15.6 I encounter an error. I am using the following cmake line:
```
cmake .. -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
```
gfortran, gcc, and g++ are all GNU version 10.2.0.
The error is:
```
/Users/wddawson/Documents/NTPoly/Bench/dbcsr/build/src/tensors/dbcsr_tensor_api_c.F:2943:23:
2943 |          c_col_major = col_major
|                       1
Error: Possible change of value in conversion from LOGICAL(4) to LOGICAL(1) at (1) [-Werror=conversion]
/Users/wddawson/Documents/NTPoly/Bench/dbcsr/build/src/tensors/dbcsr_tensor_api_c.F:2417:39:
2417 |       c_dbcsr_t_iterator_blocks_left = dbcsr_t_iterator_blocks_left(iterator)
|                                       1
Error: Possible change of value in conversion from LOGICAL(4) to LOGICAL(1) at …
```
> Type conversion compilation error fix

- src/acc/acc.h
- src/acc/acc_libsmm.h
- src/acc/cuda/acc_cuda.h
- src/acc/hip/acc_hip.h
- src/acc/libsmm_acc/libsmm_acc.cpp
- src/acc/libsmm_acc/libsmm_acc_init.cpp
- src/acc/libsmm_acc/libsmm_acc_init.h
Introduced enumeration libsmm_acc_data_t collecting macro symbols like dbcsr_type_real_8 (LIBSMM/ACC interface); this is for reusing the same definitions in every backend implementation (centralized type definition). Cleanup ACC/main interface. Prevent compilation warning about non-const string literal (CUDA/HIP header). Introduced NO_DBCSR_TIMESET to get rid of circular dependency (simplifies Makefile for upcoming changes/sample/driver code).
Note: CUDA/HIP build may need revisit; currently the ACC/CUDA backend depends on LIBSMM/ACC due to initialization code (previously the dependency edge was supposedly limited to the other way around: LIBSMM uses backend). Further, CUDA/HIP backend now not only depends on LIBSMM/ACC but also on DBCSR main library due to timeset functionality.
> Revised ACC interface

- src/acc/README.md
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/cuda/Makefile
- tests/dbcsr_acc_test.c
Added some test code (carry-forward from OpenMP/backend experiments), which exercises the ACC interface in an abstract fashion (backend agnostic); building this test may be integrated later with CMake infrastructure. Added two benchmark drivers (matrix transpose and multiplication). Added Makefile to build test and driver in a stand-alone fashion using the CUDA based backend (please note, the Makefile is not as sophisticated as the CMake based tool chain, however, it is meant to be simple or easy to adjust for the local environment).
> Stand-alone benchmarks and test for ACC/LIBSMM interface

- .ci/daint.cscs.ch/Jenkinsfile
- cmake/CompilerConfiguration.cmake
- src/acc/acc_bench_smm.c
- src/acc/acc_libsmm.h
- src/acc/dbcsr_acc_devmem.F
- src/acc/libsmm_acc/libsmm_acc.cpp
- src/mm/dbcsr_acc_operations.F
- src/mm/dbcsr_mm_accdrv.F
- tests/CMakeLists.txt
- tests/dbcsr_test_scale_by_vector.F
Introduce the c_stream for cuBLAS to avoid race-condition due to no thread-safe cublas DGEMM. See #389
> Cublas stream bug #389

- src/acc/acc.h
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/acc_libsmm.h
- src/acc/libsmm_acc/PACKAGE
- src/acc/libsmm_acc/libcusmm/PACKAGE
- src/acc/libsmm_acc/libsmm_acc_init.cpp
ACC interface: introduced companion of libsmm_acc_init (libsmm_acc_finalize). Fixed memory leak (acc/acc_bench_smm). Correctly markup symbol of libsmm_acc_init (declared in acc_libsmm.h as extern "C"). Adjusted PACKAGE dependency (LIBSMM/ACC). Code cleanup.
> ACC interface update

- .ci/daint.cscs.ch/cray.build.sh
- .ci/daint.cscs.ch/cray.test.sh
- .ci/daint.cscs.ch/gnu.build.sh
- .ci/daint.cscs.ch/gnu.test.sh
- .ci/daint.cscs.ch/intel.build.sh
- .ci/daint.cscs.ch/intel.test.sh
- .ci/daint.cscs.ch/ocl.build.sh
- .ci/daint.cscs.ch/ocl.test.sh
- cmake/CompilerConfiguration.cmake
- src/CMakeLists.txt
As pointed out by @hfp in #425
> Make nvToolsExt conditional on WITH_CUDA_PROFILING

- docs/guide/2-user-guide/1-installation/1-cmake-build-recipes.md
- docs/guide/2-user-guide/1-installation/3-using-dbcsr-in-a-cmake-project.md
- docs/guide/2-user-guide/1-installation/index.md
CMake 3.17 is now a requirement, and the Daint installation info was outdated.
Should we also add `spack install` instructions? There is no mention of it, but basically what I want is:
```shell
spack install dbcsr +rocm              # will build a lot of things including llvm-amdgpu and rocblas
spack install dbcsr +cuda              # will just download cuda
spack install dbcsr +opencl ^cuda      # possible since yesterday
spack install dbcsr +opencl ^amdopencl # there is an AMD developer wrapping this package, to be released soon
```
> Update some versions in the docs

- docs/guide/2-user-guide/1-installation/index.md
Bit of a trivial PR, but there are ugly looking borders around every line of example code here: https://cp2k.github.io/dbcsr/develop/page/2-user-guide/1-installation/index.html. So my guess is you have to specify the language to something.
> Remove error borders in docs example code

- src/acc/opencl/README.md
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
Attempt to (optionally) split devices into subdevices (`ACC_OPENCL_DEVSPLIT`). This enables CP2K/DBCSR to load MPI-ranks onto subdevices (simply discovered as devices as per `c_dbcsr_acc_get_ndevices`). Note such device is treated as an aggregate device by default and `ACC_OPENCL_DEVSPLIT` is completely optional.
* Raised ACC_OPENCL_DEVICES_MAXCOUNT to better accommodate subdevices.
* Minor rephrase; removed red boxes around verbatim section (documentation).
* Documented ACC_OPENCL_DEVSPLIT.
Unrelated: avoid warning about (invalid) "#pragma OPENCL EXTENSION all: enable" (it can only be "disable" according to OpenCL spec.). However, for some OpenCL stacks this comes handy and without this warning. Main point is most platforms enable all extensions by default but at least one not.
> ocl: expose multiple tiles/subdevices as devices

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
Enabled FP atomic-add when permitted/supported (device specific)
* Introduced c_dbcsr_acc_opencl_device_name to confirm the name of the given device.
* Determine host-device uniform memory (c_dbcsr_acc_opencl_info_devmem).
* Refined handling ACC_OPENCL_DEVTYPE (cpu, gpu, acc, all, other).
* Refined pruning device list (all kinds of devices).
* Adjusted sorting GPUs (device order).
Improved tune_multiply.py
* Avoid potential error due to reading file still open from write.
* Extended error/exception handler to cover file-read errors.
* Made TYPEID a numeric value (int).
> oclacc: refined GPU order, make use of atomic_add when possible

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/acc.h
- src/acc/acc_bench_smm.c
- src/acc/acc_libsmm.h
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/README.md
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/kernels/transpose.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- tests/dbcsr_acc_test.c
Implemented geometric mean of kernel performance (presented at end of execution/program)
* Perf. measurement is based on profiling OpenCL's queues (flushes queue for every measurement).
* Generally show "performance" rather than execution time (for more meaningful values).
* Higher log-level/s: print performance for every kernel execution.
* Updated documentation accordingly.
Other changes:
* Cleanup: Removed some compile-time settings (due to corresponding runtime setting or due to default state).
* Benchmarks: fixed calculation which was incorrectly introduced by copy/pasting from transpose benchmark.
* OCLBE: implemented profiling queue events (ACC_OPENCL_VERBOSE=3 and higher). Code cleanup.
* Kernels: avoid dynamically indexing private arrays (registers).
* Libsmm: release kernels …
> ocl verbose: profile queues and performance output

- .cp2k/makedep.py
* Removed superfluous fhandle.close().
* Open files UTF8-encoded (CP2K).
* Fixed some typos.
> makedep.py: match CP2K's makedep.py

- .ci/daint.cscs.ch/cray.build.sh
- .ci/daint.cscs.ch/cray.test.sh
- .ci/daint.cscs.ch/gnu.build.sh
- .ci/daint.cscs.ch/gnu.test.sh
- .ci/daint.cscs.ch/intel.build.sh
- .ci/daint.cscs.ch/intel.test.sh
- .ci/daint.cscs.ch/ocl.build.sh
- .ci/daint.cscs.ch/ocl.test.sh
- examples/CMakeLists.txt
- src/CMakeLists.txt
Account for an [updated](https://github.com/cp2k/dbcsr/pull/437#issuecomment-801154121) Daint-CI (CMake, etc), and counter `-Werror` with newer GNU Compiler (certain translation units).
( Unrelated: updated LIBXSMM. )
> updated daint-ci

- .cp2k/Makefile
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
* Enabled building DBCSR/OpenCL when part of CP2K build process (tested).
* Stand-alone (exts/dbcsr) compilation with OpenCL backend (tested).
OpenCL backend
* Include header-only LIBXSMM if "-I/path/to/libxsmm/include" is given.
* Produce expected compile-time error (cannot find "libxsmm_source.h").
* Special path for 64-bit atomics on 2 elements of 32-bit data.
> Enabled legacy build-integration with CP2K/Makefile

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
* Made libsmm_acc_transpose retry building a kernel if WG-size is exceeded (TODO: introduce tiles).
* Disabled thread-local context. Quiet error(s) when releasing thread-local contexts.
* Avoid potential compilation error if cl_khr_int64_base_atomics is not supported.
* Repetitions per experiment (tune_multiply.py).
* Skip adding zeros (atomic add).
> ocl: collection of minor fixes and improvements

- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- tests/dbcsr_test_multiply.F
* Made ATOMIC_ADD2_GLOBAL more conditional/prohibitive.
* Fixed potential compiler warning.
* Fixed tracking indexes.
Improvements of built-in validation
* Use consistent expression for tolerance/check and console output (dbcsr_test_multiply.F).
* Limit OPENCL_LIBSMM_DEBUG to OPENCL_LIBSMM_DEBUG_SMM by default.
* Rely on single scratch buffer in case of debug/validation.
* Introduced OPENCL_LIBSMM_DEBUG_EXIT.
* Reduced/more focused debug output.
Omit reloading the same B-matrix from global memory by copying B-tile into private memory.
* Avoiding to load same B-tile seems to be not beneficial (disabled).
> ocl: fixed incorrect kernel/case/validation

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/README.md
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Record and print the (running median of the) stack_size (SMM/transpose kernels).
* Estimate per-kernel (device-)performance from the embedded parameters (auto-tuning).
* Introduced opencl_libsmm_perfest_t to support opencl_libsmm_read_params.
* Rely on geometric mean for performance estimate.
Other
* Delete/backup existing CSV-file if no JSON-file was found (tune_multiply.py).
* Updated documentation (minor).
* Avoid C++ keyword in C code.
* Improved portability.
> ocl-insights: improved/extended output (ACC_OPENCL_VERBOSE)

- src/acc/opencl/README.md
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
* Revert back to profiling the OpenCL queue rather than host-side/asynchronous launch timing.
* Adjusted console/verbose output format (stacksize).
* Avoid unnecessary profiling or data collection.
> ocl-verbose: improved previously introduced data collection (verbose mode)

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.sh
* Operate on a unique list of triplets (tune_multiply.sh). Adjusted documentation.
* Made ACC_OPENCL_DEVSPLIT=1 the default (disable with ACC_OPENCL_DEVSPLIT=0).
* Code/format cleanup.
> ocl-misc: adjusted some defaults and updated documentation

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Additional/alternative tunable names (OPENCL_LIBSMM_SMM_~): BS, BM, BN.
* Introduced DEV=2 to perform static code-analysis (Makefile).
* Only load device-specific/matching tuned parameters.
* Kernel code cleanup (renamed variables, etc).
* Updated LIBXSMM (Daint-CI/OpenCL).
acc_opencl.sh
* Handle empty DEVICE column, Windows newline (CSV), and prefer OPENCL_LIBSMM_PARAMS_DEVICE=NULL if unknown.
* Only attempt to delete the OFILE if it is a header-file (not a pseudo file like /dev/stdout).
* Include device name used to tune parameters (OPENCL_LIBSMM_PARAMS_DEVICE).
* Account for macOS' wordcount command (which adds leading spaces).
* Check/limit to single/consistent device (parameter collection).
* Disallow space character as separator (CSV file).
* Handle an optional DEVICE column in …
> oclreg: use tuned parameters if device matches original target

- docs/CMakeLists.txt
- src/acc/acc_bench.h
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/libsmm_acc/libsmm_acc.cpp
- src/acc/libsmm_acc/libsmm_acc_benchmark.cpp
- src/acc/libsmm_acc/libsmm_acc_benchmark.h
- src/acc/opencl/Makefile
- src/core/dbcsr_config.F
- src/mm/dbcsr_acc_operations.F
- src/mm/dbcsr_mm_common.F
- src/mm/dbcsr_mm_sched.F
- tests/dbcsr_performance_driver.F
- tests/dbcsr_tensor_unittest.F
- tests/dbcsr_test_csr_conversions.F
- tests/dbcsr_unittest1.F
- tests/dbcsr_unittest2.F
- tests/dbcsr_unittest3.F
- tests/dbcsr_unittest4.F
ACC benchmark drivers (SMM and Transpose)
* Improved validation output and reintroduced error margin (ACC_BENCH_SMM_EPSILON).
* Validation still does not control result code unless CHECK is given
* (CHECK=1 is a real number "1.0" scaling the ACC_BENCH_SMM_EPSILON).
* Wrap libxsmm_itrans_batch depending on whether OpenMP is present or not.
* OpenMP-parallel data initialization and code cleanup (INIT_MAT).
* Made OpenMP runtime optional (and libxsmmext library).
Use consistent stack-initialization for CUDA/HIP and OpenCL benchmarks
* Made init_stack and INIT_MAT available (acc_bench.h).
* Removed unused arguments of stackInit function.
Other
* Target doc_copy_examples does not exist if WITH_EXAMPLES=OFF.
* Marked libsmm_acc_process as extern "C" (CUDA/HIP backend).
* Code cleanup (comments, …
> ACC benchmarks and code cleanup

- tests/dbcsr_tensor_test.cpp
The test in question looks like behind the original plan (support for complex-valued matrices). The issue could not been reproduced even when using clang (default compiler under BSD). However, the problematic code was removed (unused).
> Removed non-compiling dead code. Avoid unused variable warning

- src/acc/acc_bench_smm.c
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/tune_multiply.py
* Avoid normalizing the relative error but consider it in a normalized fashion (acc_bench_smm).
* Revised short command line arguments. Introduced argument to customize size of SMM-batch.
* Fixed taking custom number of repetitions into account.
* Introduced ELEM_TYPE build key (make ELEM_TYPE=float).
* Slightly revised documentation.
> ocl-misc: improved Makefile and tune_multiply.py

- src/acc/libsmm_acc/libsmm_acc.cpp
JIT compilation fails in DBCSR with newer rocm versions (>=4.1)
because there is a mismatch detected between the target id passed to
hiprtcCompileProgram and what hiprtc already passes by default.
hiprtcCompileProgram now honors compile options passed to it. It
also by default has always passed the target ids of the default
device to the compiler, so we don't have to pass this architecture
string as a compile option again. This also helps avoid any
changes to DBCSR when target ids are modified for future AMD GPUs.
> Remove gpu arch passed to hiprtc

- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Introduced type-id for kernel-code (TN), and adjusted atomic_add_global_xchg code-path (PTX).
* Removed unnecessary barrier and made another (necessary) barrier conditional (at compile-time).
* Makefiles: Improved detecting OpenCL, use ARCH_NUMBER=80 if WITH_GPU=A100 (rely on V100-params).
* Fixed and adjusted ATOMIC_ADD2_GLOBAL code-path.
> ocl-misc: various/minor SMM-kernel improvements and fixes

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/README.md
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/opencl/README.md
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
* Documented environment variable DEVICE for acc_bench drivers.
* Allow to set active device per environment variable (DEVICE).
* Clarified ACC_OPENCL_DEVTYPE (OpenCL BE documentation).
* Adjusted default (OpenCL BE).
> ocl-bench-doc: non-default active device for acc_bench drivers and documentation

- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/tune_multiply.py
* Apparently, performance can be significantly better even against auto-tuned CUDA kernels.
* While prime kernels like 23x23x23 can still be improved, perf. seems to be mostly on par.
Details
* tune_multiply.py: updated documentation and mention merge/update functionality.
* multiply.cl: introduced COPY_B (and disabled copying B-tile into private memory).
* multiply.cl: reqd_work_group_size (known at compile-time).
* multiply.cl: several improvements targting Nvidia GPUs.
* multiply.cl: no opencl_unroll_hint before OpenCL 2.0.
* multiply.cl: hint unrolling/not unrolling loops.
* multiply.cl: licm some loop-bound calculation.
* multiply.cl: improved A-transpose loop.
* acc_bench_smm: adjusted acceptable error margins.
* acc_bench_*: dev-id only if non-zero (non-default).
* acc_opencl.sh: …
> ocl-perf: closed perf gap between OpenCL and CUDA

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/acc_getenv.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Auto-tune parameters based on pretuned values/state (parse verbose output of acc_bench_smm).
* Introduced OPENCL_LIBSMM_SMM_BANK_C/OPENCL_LIBSMM_SMM_BC tunable boolean parameter.
* Some preparation for padded problem sizes (ACC_OPENCL_OVERMALLOC, etc.).
* Fixed dumping IR (replaced ACC_OPENCL_BINARYSIZE with arbitrary size).
* Build OpenCL kernels with latest OpenCL standard (-cl-std=CLx.y).
Other:
* Handle multiple getenv per line (acc_getenv.sh).
* Revised verbose output (more regular, etc.).
* Made clEnqueueWriteBuffer non-blocking.
* Validate final auto-tuned result.
> ocl-tune: detect and avoid bank-conflicts, improved auto-tuning process

- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Issue warning if opencl_libsmm_read_params fails (code path for embedded parameters).
* Introduced ZERO to avoid type-conversion even from literal value (PTX).
* Improved controlling code-paths, and adjusted defaults.
* Fixed allowed range of tuned parameters (AA, and AB).
* Fixed workshare for SHARED_A and SHARED_S.
* Simplified partial workshares.
> ocl: introduced SHARED_C along with tunable parameter

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/Makefile
- src/acc/opencl/acc_getenv.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/kernels/transpose.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Introduced dump-level for external preprocessor (ACC_OPENCL_DUMP=1), dump IR/binary (ACC_OPENCL_DUMP=2).
* Introduced tunable parameter for limited loop-unroll (OPENCL_LIBSMM_SMM_LU=0|1).
* Introduced tunable parameter for handling WG-size (OPENCL_LIBSMM_SMM_WG).
* Introduced ATOMIC_INC_NZ incl. tunable parameter.
General:
* Removed legacy/alternative names of tunable parameters. Updated documentation.
* Support CPPFLAGS and allow flags such as -d, -d, --comments, or --debug (acc_opencl.sh).
* Keep comments when embedding kernel code (acc_opencl.sh -c).
* Fixed splitting device into sub-devices.
tune_multiply.py:
* Implemented verbose output (experiment info when auto-tuning parameters).
* Omit benchmark invocation if update is launched with given device name.
* Uninstall signal handler …
> ocl: additional tunable parameter

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Automatically apply CL-standard compile-flag (c_dbcsr_acc_opencl_kernel).
* Apply vendor definition (c_dbcsr_acc_opencl_kernel).
* Fixed __OPENCL_VERSION__ based on real version.
> ocl: match production source and dumped source

- .cp2k/Makefile
When linking CP2K with OpenBLAS that is built with g++ with OpenMP support and enabling DBCSR's HIP backend, if hipcc is used to build DBCSR's cpp files, then in the final CP2K executable we see two OpenMP runtimes linked. One (libgomp.so) that OpenBLAS pulled in, and another (libomp.so) that DBCSR pulled in. To avoid this, it is best to build DBCSR using the same host compiler as CP2K and add a flag to indicate that the HIP_PLATFORM is AMD. This commit and an equivalent commit to CP2K will rely on the setting of USE_ACCEL to determine which compiler and flags to use for compiling DBCSR's cpp files for AMD devices.
I tested on AMD and NVIDIA devices, but not with the OpenCL backend. I changed how the OpenCL source files are included in the build so that they don't get pulled in when …
> Fix CP2K Makefile to build DBCSR correctly with HIP support

- .ci/daint.cscs.ch/ocl.build.sh
- .cp2k/Makefile
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/acc_triplets.sh
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
- tests/dbcsr_acc_test.c
* Validate result buffers at once (including excess area/padded space).
* Adjusted error margin according to revised measure (libxsmm_matdiff).
* Always print maximum error if multiple runs were performed.
* Tests: runtime and environment information (test log).
* Tests: use datamash to produce summary statistics.
* Fixed condition for double-update (atomic).
* Improved ACC_OPENCL_DUMP=1.
Auto-tuning
* Only auto-configure kernel if no external configuration is supplied.
This allows to discover the full space of tunables.
* Corrected handling fixed parameters (tune_multiply.py).
* Introduced acc_triplets.sh.
Other:
* Avoid init/finalize within loop (growing memory consumption depending on OpenCL impl).
Note: within loop was meant to exercise tear-down, etc. (but not feasible).
* benchmark: …
> ocl: fixes, tests and common utilities

- src/acc/acc_bench_smm.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
* Transpose: alternative/shorter environment variable (BLOCK_M/BM) similar to SMMs.
* Transpose: allow "0" to refer to the default setting.
* Benchmark driver: adjusted error bounds.
* Improved ACC_OPENCL_DUMP=1.
> ocl: introduced tuning-level to reduce/preset list of tuned parameters

- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
* tune_multiply.py: avoid parameter validation in case of SIGINT
(user hitting CTRL-C wants to avoid running application)
* tune_multiply.sh: fixed evaluating acc_triplets.sh.
* tune_multiply.sh: fixed path to acc_triplets.sh.
* opencl_libsmm.c: removed hidden BC parameter.
> ocl: improved auto-tuning utilities

- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
* Allow successful libsmm_acc_init if given parameter file cannot be loaded or does not exist (OPENCL_LIBSMM_SMM_PARAMS).
* Introduced OPENCL_LIBSMM_SUITABLE which allows to disable suitability-check even if support/enabled at compile-time.
* If PARAMS_DIR is given, attempt to automatically determine GPU-environment (OPENCL_LIBSMM_SMM_PARAMS).
* Support unsuitable kernel (return code -1) without failing the benchmark/test (acc_bench_*).
* Run (optional/disabled) suitability test even if OPENCL_LIBSMM_SMM_PARAMS is given.
* Load embedded parameters if loading from file failed (soft error).
* Print number of test cases. Fixed title of test cases (Makefile).
* Track and print performance of seed- or initial configuration.
* Removed debug code (acc_bench_trans).
> ocl: improved handling loaded vs embedded parameters

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* tune_multiply.py: introduced "retain" and "delete" category (suitable for "rm" command).
* Extended LU-parameter (previously "LimitUnroll", now "LoopUnroll").
* Adjusted c_dbcsr_acc_opencl_device_level.
> ocl: improved auto-tuning script to keep collection of tuned results up-to-date

- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/opencl_libsmm.c
* Removed test-target from all-target (Makefile/CUDA/OpenCL).
* Introduced try_build_options (c_dbcsr_acc_opencl_kernel).
* Avoid warning with some versions of Clang (acc_bench_*).
* Account for common directory (Makefile/CUDA).
* Adjusted some configuration (OpenCL).
> ocl: Makefile to account for CUDA/HIP common bits

- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Implemented collecting garbage streams (c_dbcsr_acc_stream_destroy).
Other/fixes:
* c_dbcsr_acc_opencl_kernel (NDEBUG): assume extensions are confirmed upfront.
* Warning about unsupported extension. Revised error/warning messages.
* Introduced separate control for barriers (OPENCL_LIBSMM_SMM_BARRIER).
* Modernized barrier to C11 form (if permitted).
* Use C11 atomics (cl_intel_global_float_atomics).
* Implemented cl_ext_float_atomics (untested).
* Avoid using stateful strtok (nested usage).
* Kernel: fixed syntax error (BS=1 code-path).
* Kernel: some (minor) kernel optimizations.
* Refined "all" target (Makefile).
> ocl: completed c_dbcsr_acc_device_synchronize and fixes

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
* Migrated global c_dbcsr_acc_opencl_streams and c_dbcsr_acc_opencl_nstreams into c_dbcsr_acc_opencl_config.
* Migrated global c_dbcsr_acc_opencl_ndevices into c_dbcsr_acc_opencl_config (ndevices).
* Redefined ACC_OPENCL_STREAMS_MAXCOUNT to count on a per-thread basis.
* Encapsulated thread-local context into c_dbcsr_acc_opencl_context().
> ocl: implemented thread-local context and device

- src/acc/acc_bench.h
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/kernels/transpose.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Introduced (optionally) querying device-type (c_dbcsr_acc_opencl_device_level).
* Recalculate block size to ensure minimum requested WG-size (WS).
* Fixed variable name in certain code-path (transpose kernel).
* Adjusted help messages and tuning level (tune_multiply.py).
* Kernel: fixed taking TB and TC into account.
* Kernel: code cleanup.
* Makefile dependency.
> ocl: fixes and code cleanup

- docs/guide/2-user-guide/1-installation/index.md
- docs/guide/2-user-guide/4-gpu/index.md
- docs/guide/3-developer-guide/3-programming/1-overview/index.md
- docs/guide/3-developer-guide/4-performance/2-just-in-time-compilation.md
* Revised section about "Just-In-Time Compilation" to be backend-agnostic and more general.
* Subsection about auto-tuning an OpenCL/LIBSMM-kernel (User Guide rather than Developer Guide).
* Subsection about auto-tuning CUDA/HIP-kernels (User Guide rather than Developer Guide).
* Some (minor) cleanup (relative URLs).
> Documentation: section in User Guide about auto-tuning GPU-kernels

- docs/guide/2-user-guide/4-gpu/index.md
- docs/guide/3-developer-guide/4-performance/2-just-in-time-compilation.md
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/smm/opencl_libsmm.c
* Doc: account for timing report now supported by the OpenCL backend.
* Doc: improved spelling and inline-format of certain terms.
Other:
* Allow to potentially include opencl_kernels.h multiple times.
> ocl: DBCSR perflog (JIT timing) for OpenCL based LIBSMM

- src/acc/acc_triplets.sh
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
tune_multiply.sh
* Introduced command-line flags/options and avoid positional/non-optional arguments.
* Handle if no triplet spec given; improved error/help message.
* Introduced directory arguments for JSON-files.
* Introduced option to set tuning-level.
* Implemented update-mode.
acc_triplets.sh
* Handle if no triplet spec given; improved error/help message.
* Improved checking arguments and compliance with Shellcheck.
Other
* Cleanup (tune_multiply.py).
* Updated documentation.
> ocl: improved scripts for auto/bulk-tuning kernels

- docs/guide/2-user-guide/4-gpu/index.md
The keyword `cpus_per_node `is misleading and needs to change to `cpus_per_task`.
> Misleading keyword cpus_per_node

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
* Synchronize c_dbcsr_acc_opencl_set_active_device to enable adopting/sharing contexts.
* Renamed c_dbcsr_acc_opencl_device_id to c_dbcsr_acc_opencl_device_uid.
> ocl: synchronize c_dbcsr_acc_opencl_set_active_device

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/opencl_libsmm.c
* Try reading OPENCL_LIBSMM_SMM_PARAMS-value as kernel parameters.
* Show thread-local active devices for each PID (verbose mode).
> ocl: additional verbose output

- src/acc/cuda_hip/acc_dev.cpp
- src/acc/dbcsr_acc_device.F
- src/acc/libsmm_acc/kernels/smm_acc_common.h
- src/core/dbcsr_config.F
- src/mm/dbcsr_mm_accdrv.F
- src/mm/dbcsr_mm_cannon.F
This PR attempts to simplify the DBCSR HIP backend with the following changes (not ready to merge yet, but I am creating the PR to get them tested more thoroughly):
- Remove the use of posterior streams, use only one type of stream. In the current form, we only have priority streams but they are actually low priority, blocking streams. In my tests, higher priority, non-blocking streams seemed unnecessary.
- There is a unique stream assigned per CPU thread for a given process. This removes race conditions seen when running the HIP backend with the original code.
- A device synchronize after the copy of left and right matrices and before the start of the multiply parallel region removes the need for repeatedly checking for event completions in the beginning of every iteration of the loop.
- …
> Simpler hip backend

- src/core/dbcsr_config.F
- src/mm/dbcsr_mm_accdrv.F
- src/mm/dbcsr_mm_sched.F
* Arguments of dbcsr_set_config/dbcsr_get_config remain with terminology "posterior" and priority".
* Integration with CP2K to stay compatible.
> cleanup configuration related to #499

- docs/guide/2-user-guide/4-gpu/index.md
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
* Parse MxNxK rather than "M N K" (tune_multiply.py).
* Updated documentation accordingly.
* Print failing configurations.
Other:
* Revised c_dbcsr_acc_event_query for clarity.
* Adjusted precondition of suitability-info.
> ocl: revised auto-tuning script

- src/core/dbcsr_config.F
- src/core/dbcsr_lib.F
The type dbcsr_config_type is statically initialized. However, a number of properties are derived at runtime, e.g., accdrv_streams, accdrv_buffers, comm_thread_load, and mm_driver. Even DBCSR's unit tests never call dbcsr_set_config, which is abused to initialize value of aforementioned properties. Further, dbcsr_get_default_config also only relied on static initialization of dbcsr_config_type (rather than at least copying dbcsr_cfg).
> fixed potentially inconsistent configuration

- src/core/dbcsr_config.F
* Note: omp_get_max_threads() returns one if inside of parallel region (nested OMP not enabled).
* Avoid resetting initial value (when potentially inside of a parallel region).
> revised #516: ensure nthreads and dependent values are initialized once

- src/acc/opencl/README.md
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
- tests/dbcsr_acc_test.c
* Account for c_dbcsr_acc_device_synchronize called outside of parallel region.
* Cleaned experimental runtime settings. Updated documentation accordingly.
* Removed ACC_OPENCL_THREADLOCAL_CONTEXT and ACC_OPENCL_STREAMS_MAXCOUNT.
* Removed testing races between stream create/destroy (dbcsr_acc_test).
* Attempt to share contexts more aggressively.
* Code cleanup
> ocl: revised backend to improve c_dbcsr_acc_device_synchronize

- docs/guide/3-developer-guide/4-performance/2-just-in-time-compilation.md
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/mm/dbcsr_mm.F
* Made svm_interop (c_dbcsr_acc_opencl_config_t) only available in case of ACC_OPENCL_SVM.
* Migrated remaining globals into c_dbcsr_acc_opencl_config (contexts and devices).
* Streams statistics and adjusted termination message.
* Attempt to distribute streams over threads.
Introduced LIBXSMM dependency for OpenCL BE (not only LIBSMM)
* Leveraged macros and more functions from LIBXSMM.
* Introduced ACC_OPENCL_MALLOC_LIBXSMM.
Other
* Fixed typo (documentation).
> ocl: fixed c_dbcsr_acc_device_synchronize and cleanup

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
* Note: ACC_OPENCL_DEVICE can be used to control/adjust MPI rank-device association.
* Fixed ACC_OPENCL_DEVICE to prune the number of device to only expose the requested ID.
* Extended c_dbcsr_acc_opencl_device_id to determine global device-ID ("true" ID).
* termination message (ACC_OPENCL_VERBOSE=1) shows the true ID.
* Improved termination message to shorter list of streams.
> ocl: fixed/improved selecting device per ACC_OPENCL_DEVICE

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
- tests/dbcsr_acc_test.c
* Fixed ACC_OPENCL_DUMP in case of multiple threads dumping the same kernel.
* Do not test if no device was found (dbcsr_acc_test).
> ocl: fixed/improved initialization, finalization and handling errors

- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Replaced references/pointers to/into reg-backed arrays (access-macros).
* Strip C++ style comments from kernel's source (ACC_OPENCL_DUMP).
* Reworked unroll-control to be part of the kernel-source.
* Implemented new kernel/code-path (BK=1).
* More detailed error/verbose message.
* Adjusted Makefile.
> ocl: added new code-path to SMM-kernel source

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Enable FP-atomics in source if __opencl_c_ext_fp64_global_atomic_add is defined.
* More compact expressions expanded from macros and more compact code-format.
* Implemented using FP-atomics without extension/confirmation.
* Disable extensions if confirmation fails.
> ocl: support variety of FP-atomics

- src/acc/opencl/smm/tune_multiply.py
* Properly wrap if an environment variable (tuneable) is fixed or if it yields a value.
* Avoid tuning into WG=2. Fixed default of AP-parameter.
* Disabled tuning AL-parameter by default.
* Enabled auto-tuning for WG=-1.
* Tune BK-parameter by default.
> ocl: adjusted script for auto-tuning SMM-kernels

- src/acc/acc_bench_smm.c
- src/acc/acc_triplets.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
* Correctly reproduce default values (if not present in JSON).
* Outer k-loop for code-path using general tiles.
* Fixed issues pointed out by static analysis.
* Decoupled WG=-1 and BK=1 (introduced WG=-2).
* Improved BOUNDL/BOUNDU (acc_triplets.sh).
* Adjusted range of WG-parameter.
* Omit barriers if possible.
* Improved handling errors.
* Adjusted code-format.
* Adjusted tolerance.
> ocl: various minor improvements and additional kernel code-path

- examples/dbcsr_example_3.cpp
- tests/dbcsr_test.cpp
Removed invalid suffixes from literal double-precision numbers. Note, 'f' for single-precision exists but 'd' is implied (if a fractional part is given).
> Removed invalid suffixes from literal DP FP-numbers

- src/data/dbcsr_ptr_util.F
- src/mpi/dbcsr_mpiwrap.F
- src/ops/dbcsr_operations.F
* If __DBCSR_DISABLE_WORKSHARE defined, the parallel WORKSHARE construct is avoided.
> introduced __DBCSR_DISABLE_WORKSHARE

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Introduced opencl_libsmm_write_params and reworked verbosity/parsing of tunable parameters.
* Improved _DEBUG/trace information and diagnostics.
* Revised c_dbcsr_acc_opencl_set_active_device.
* Revised c_dbcsr_acc_opencl_create_context.
* Revised c_dbcsr_acc_stream_create.
* Fixed __VA_ARGS__ in some macro.
* Lock stdout/stderr stream.
> ocl: revised printing/parsing tunable parameters

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* Ensure device-dependent configuration is updated during c_dbcsr_acc_set_active_device.
* Reworked matching kernel-parameters (tunables) against devices (UID).
* Improved order/combining tunables (built-in, file, environment).
* Fixed/implemented matching devices (tunable parameters).
* Allow to build with device-match enabled by default.
* Introduced ACC_OPENCL_DEVMATCH environment variable.
* Reworked/improved opencl_libsmm_read_smm_params.
* Fixed walking OoB (reading set of tunables).
* Revised condition (OPENCL_LIBSMM_SUITABLE).
* Print device's UID (ACC_OPENCL_VERBOSE=2).
* Account for revised interface (LIBXSMM).
> ocl: reworked matching device when loading tunables

- src/core/dbcsr_lib.F
- src/mm/dbcsr_mm.F
* Call acc_init and acc_finalize in dbcsr_init_lib_pre and dbcsr_finalize_lib respectively.
* Note: libsmm_acc_init/finalize is missing (and up to MM component of DBCSR).
* Call libsmm_acc_init and libsmm_acc_finalize (MM component).
> Issue #535: call acc_init and acc_finalize prior to other ACC routines

- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/mm/dbcsr_mm_hostdrv.F
* LIBXSMM_GEMM_PRECISION -> LIBXSMM_DATATYPE (in preparation for LIBXSMM 2.0).
* Note: using LIBXSMM_DATATYPE is still backward compatible (older LIBXSMM).
* Other: Adjusted format of numbers to show two significant digits (ms).
> Preparation for LIBXSMM 2.0

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
* Attached stream priority to stream's handle and infrastructure to get attached info.
* Depend on priority for synchronization (flushing rather than finishing work).
* Enabled stream priorities even if not permitted (vendor).
* Account for initialized BE but no devices found.
* Revised trace control and assertions.
* Soft-error if releasing context fails.
* Extended/revised ACC_OPENCL_FLUSH.
* Removed some WORKAROUND marker.
> ocl: revised implementation of c_dbcsr_acc_device_synchronize

- src/acc/libsmm_acc/libsmm_acc_init.cpp
* Resolves crash when application terminates.
> Fixed calling libsmm_acc_finalize multiple times for CUDA/HIP based LIBSMM.

- src/acc/acc_bench_smm.c
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.py
* acc_bench_smm: SMM_BATCHSIZE to force batch-size (aka stack-size).
* Introduced S-(pseudo-)parameter, and handle kernel-kind (SMMs).
* Fixed OPENCL_LIBSMM_SUITABLE (preparation for LIBXSMM 2.0).
* Use c_dbcsr_acc_opencl_config.ndevices to track initialization.
* Include global/batch-size into tuned result-set (parameters).
* Improved type-checks (opencl_libsmm_read_smm_params).
* tune_multiply.py:: improved JSON-file pattern (CSV-file).
* tune_multiply.py: more compact creation of parameters.
* Revised and fixed LIBXSMM-version specific code-paths.
* Print stream/execution priority (ACC_OPENCL_VERBOSE).
* SMM-kernel: disabled combination of BS=1 and AL=1.
* Better sanitize loaded parameters.
* Adjusted verbose output.
> ocl: generate and select kernel for shorter stack-sizes

- src/acc/opencl/README.md
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/tune_multiply.sh
* tune_multiply.sh: fixed file pattern.
* Updated documentation.
> ocl: fixed kernel variant using sub-group intrinsic

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Moved profiling queues up by two verbosity levels (level 3/4: host timer, 5/6: events/device-timer).
* Fixed config's WG-size not copied in some cases.
* Fixed another case of AL=1 flaw (SMM-kernel).
* Print kernel runtime (ACC_OPENCL_VERBOSE).
* Updated LIBXSMM for Daint-CI.
* Adjusted some defaults.
> ocl: fixed some/non-default SMM-kernel code-path

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
- src/acc/opencl/smm/tune_multiply.sh
* Implemented cl_cache_dir (see https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md#feature-cl_cache).
* Introduced opencl_libsmm_timer_t (opencl_libsmm_timer_device, opencl_libsmm_timer_device).
* Introduced environment variable OPENCL_LIBSMM_TIMER (device|host or 0|1).
* Made some code optional (ACC_OPENCL_CPPBIN, ACC_OPENCL_SEDBIN).
* Enable ACC_OPENCL_CACHEDIR in case of __DBCSR_ACC.
* Fixed regex (tune_multiply.sh).
* Adjusted some default values.
* Updated LIBXSMM for Daint-CI.
> ocl: improved determinism for small SMM sequences/batches

- src/acc/acc_triplets.sh
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
* Made -s|--batchsize available for tune_multiply.sh. Revised script options to be more coherent.
* Always tune primary kernel and avoid automatically enabling kernel for small batches.
* Only consider a default size if the problem-size is not specified.
* Pass problem-size when launching benchmark/executable.
* Adjusted default (BS=1 kernel).
> ocl: revised wrapper/scripts related to auto-tuning SMMs

- src/acc/acc.h
- src/acc/acc_libsmm.h
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
* Moved prototypes/declarations of timeset/timestop to ACC-interface.
* Added missing barrier in certain kernel code-path (subgroups).
* Reworked device_synchronize to be based on stream_sync.
* Introduced ACC_OPENCL_PROFILE (using timeset/timestop).
* Renamed OPENCL_LIBSMM_SMM_ID to OPENCL_LIBSMM_SMM_DEVID,
and limited scope to loading default parameters.
* Fixed reading CSVs with device name containing WS.
* Excluded white spaces from ACC_OPENCL_DELIMS.
* Fixed calling putenv (compiler error/warning).
* Improved testing code-paths (__DBCSR_ACC).
* Adjusted auto-tuning level (wrapper script).
* Implemented ACC_OPENCL_SHARE (stride).
* Count unique streams (statistics).
* Improved handling errors.
* Adjusted tuning levels.
* Adjusted defaults.
> ocl: fixed kernel code-path and code cleanup

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
* Avoid creating unnecessary user-events (ACC_OPENCL_EVENT_CREATE).
* Automatically enable cache if cache-folder exists.
* Fixed calling function (wrong signature).
* Fixed synchronization issue.
> ocl: improved synchronization plus several fixes

- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
* Account for cb6a48d6815d35efb796963f5c14645c17e836b6.
* Allow "cpu" keyword (OPENCL_LIBSMM_TIMER).
> ocl: improved runtime setup

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/acc_opencl.h
* Disabled stream-priorities (not used in DBCSR).
> ocl: disabled stream priorities

- src/acc/opencl/smm/opencl_libsmm.c
* Note: "potential buffer overflow" so far stems from static analysis.
* Other: take OPENCL_LIBSMM_SMM_DEVID also as hexadecimal value.
> ocl: fixed potential buffer overflow

- src/acc/acc_bench.h
- src/acc/acc_bench_smm.c
- src/acc/libsmm_acc/libsmm_acc_benchmark.cpp
- src/acc/opencl/smm/opencl_libsmm.c
* Adjusted init_stack to (optionally) use an array of random numbers.
* acc_bench_smm: skip empty lines in input-file.
* Fixed corner-case (randomized stacksize).
> ocl: more reproducible input for acc_bench_smm

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/acc_bench_smm.c
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
* Fixed OOB-access if ACC_OPENCL_DEVICE specifies an invalid device.
* Print max. error even in case of failed validation (acc_bench_smm).
* Adjusted tolerance (acc_bench_smm).
> ocl: fixed OOB-access if invalid device was specified

- src/acc/acc_makedep.sh
This fixes rebuilding parameters.h (CUDA/HIP) and opencl_kernels.h (OpenCL) when GPUVER changes. There will a corresponding PR for CP2K (exts/build_dbcsr/Makefile). Currently, removing exe, obj, and lib directories in CP2K's root/build directory does not trigger rebuilding aforementioned parameter files since these files are hosted in DBCSR's source-tree. After this (and the related PR for CP2K), the parameter files are generated whenever GPUVER changes.
> acc: generate dependency based on GPUVER

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
* Removed build-time decision about ACC_OPENCL_SHARE.
* Fixed loop-bound.
> ocl: enabled fp32 kernels

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
* Renamed OPENCL_LIBSMM_DEBUG to OPENCL_LIBSMM_VALIDATE.
* Made OPENCL_LIBSMM_SUITABLE available at runtime.
* Improved suitability message (ACC_OPENCL_VERBOSE).
* Updated LIBXSM (Daint-CI).
> ocl: improved checking suitability of kernels

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/core/dbcsr_lib.F
- tests/dbcsr_acc_test.c
* Introduced ACC_OPENCL_LAZYINIT.
* Prettify.
> ocl: allow get_ndevices/set_active_device before init

- src/acc/PACKAGE
- src/acc/dbcsr_acc_init.F
- src/core/dbcsr_lib.F
- tests/CMakeLists.txt
- Setdevice is now called as part of acc_init. This problem was introduced with https://github.com/cp2k/dbcsr/commit/eb1c2688730ec5d1260c0a0cb37f71c1a4c362b6
- It is forbidden to change the device during the DBCSR execution by design, so acc_init is the correct place where to call setdevice
- This PR should fix #591 
- We still have some of the problems discussed in #422 , we use another PR for that...
- Bonus: I'm commenting acc tests on because of #427
> ACC Setdevice reordering

- src/acc/opencl/README.md
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
* Removed built-in summary statistics (ACC_OPENCL_VERBOSE).
* Made ACC_OPENCL_MEM_ZERO_KERNEL a runtime-option.
> ocl: removed code mostly used during development

- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Use host-based timer if command aggregation is enabled.
* Fixed forcing atomics (OPENCL_LIBSMM_SMM_ATOMICS).
> ocl: improved runtime settings

- docs/CMakeLists.txt
Resolves https://github.com/cp2k/dbcsr/issues/618
Successfully builds with:
- `-DBUILD_TESTING=ON`, `-DWITH_EXAMPLES=ON`
- `-DBUILD_TESTING=OFF`, `-DWITH_EXAMPLES=OFF`
- `-DBUILD_TESTING=ON`, `-DWITH_EXAMPLES=OFF`
- `-DBUILD_TESTING=OFF`, `-DWITH_EXAMPLES=ON`
Previously didn't build with `-DBUILD_TESTING=OFF`.
> Fix build when testing is disabled

- src/acc/acc_bench_smm.c
- src/acc/acc_bench_smm.sh
- src/acc/acc_triplets.sh
- src/acc/opencl/Makefile
- src/acc/opencl/acc_getenv.sh
- src/acc/opencl/acc_opencl.sh
* Limit number of parallel tasks (and ovoid oversubscribing GPUs).
* Introduced an option permitting multi-device tests (Makefile).
* Aggregated output into one locked section (acc_bench_smm).
> ocl: wrapper script to schedule an input file to multiple devices

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl_mem.c
* Protect clSVMFree (ACC_OPENCL_SVM/svm_interop).
* Call clReleaseDevice only for explicit debug.
* Compare source and destination before copy.
> ocl: code cleanup and minor fixes

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/smm/opencl_libsmm.c
* Renamed ACC_OPENCL_NULLIFY to ACC_OPENCL_DEVCOPY, and interpret as bits as flags.
* Implemented kernel-based d2d-copy kernel (ACC_OPENCL_DEVCOPY=2).
> ocl: optional/debug copy-kernel

- src/cmake/DBCSRConfig.cmake.in
CMake is complaining when dbcsr is compiled with rocm support and the package is used inside other cmake projects. We detected this while working on the cp2k cmake build.
> Fix hip detection with cmake.

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/acc_bench_smm.c
- src/acc/cuda/Makefile
- src/acc/cuda_hip/acc_event.cpp
- src/acc/opencl/Makefile
- src/acc/opencl/smm/opencl_libsmm.c
* Allow to continue benchmark if kernel is not available and if CHECK=0. Improved Makefile.
* Print rejected kernel and refined behavior of failing execution (CHECK).
* OCL: Avoid warning about dead store and about unused variable.
* CUDA: auto-detect GPU-kind using nvidia-smi (Makefile).
* CUDA: Avoid compilation warnings (-Wformat).
> acc: acc_bench_smm to continue if CHECK=0 in case of kernel not available

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/opencl_libsmm.c
* Release devices if pruned when enumerating devices (c_dbcsr_acc_init).
* Adjusted interpretation of OPENCL_LIBSMM_SMM_ATOMICS.
* Introduced ACC_OPENCL_DEVIDS (whitelist).
* Improved debug output.
> ocl: introduce ACC_OPENCL_DEVIDS whitelist of devices

- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
* Link against static library of LIBXSMM if archive and shared library are found.
* Makefile: renamed LIBOPENCL to OPENCL_LIB, and introduced OPENCL_INC.
> ocl: link libxsmm statically

- docs/guide/3-developer-guide/3-programming/1-overview/index.md
- src/CMakeLists.txt
- src/acc/opencl/acc_opencl.c
- src/mpi/dbcsr_mpiwrap.F
This PR removes the __MPI_VERSION flag to turn off code requiring the MPI 3 standard. Because MPI3 was published 10 years ago, it will be fully supported by all MPI implementations in use.
It is the equivalent to the PR cp2k/cp2k#2438 .
> Drop support for the MPI 2 standard

- src/core/dbcsr_config.F
Please correct if I am wrong: In MPI, I am not aware of the fact that "nodes" are commonly used terminology. From the numbers that are printed on top of each CP2K output, it seems to me that "numnodes" is the number of MPI processes that are used.
> Rename DBCSR MPI output that is printed on top of each CP2K run

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
* Attempt to avoid warnings about potentially uninitialized data (https://groups.google.com/g/cp2k/c/plxdnT5hqi4 - struct={0}).
* In case of loading a program from binary representation, discover kernels in program, and adopt last kernel listed (fallback).
* Support loading binary/precompiled kernels. Rely on clCreateProgramWithBinary by default rather than clCreateProgramWithIL.
* Refactored c_dbcsr_acc_opencl_kernel (c_dbcsr_acc_opencl_build_flags). Avoid dumping kernels if actually loaded from dump.
* Removed c_dbcsr_acc_opencl_stristr and use libxsmm_stristr (LIBXSMM is a hard dependency).
* Extended c_dbcsr_acc_opencl_kernel to allow filename instead of source code.
* Include compilation flags as comment into dumped source code (ACC_OPENCL_DUMP=1).
> ocl: mute warnings about potentially uninitialized data

- src/mm/dbcsr_mm_cannon.F
Some MPI implementations have high overhead when encountering a new buffer.
For the H2O-DFT-LS benchmark this change yields up to 8% speedup with OpenMPI.
> Use memory pool also for Cannon send buffers

- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
* tune_multiply.sh: ensure variable content is in correct format.
* tune_multiply.sh: fixed splitting work into parts.
* tune_multiply.py: account for missing data.
* tune_multiply.sh: fixed exit-condition.
> ocl: various fixes for auto-tuning script

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.sh
* Fixed initialization given that the OpenCL BE now fully depends on LIBXSMM.
* Using c'tor/d'tor attributes required initializing LIBXSMM in OpenCL BE.
* Introduced optional verbosity (acc_opencl.sh).
> ocl: fixed backend initialization

- .github/workflows/testing-gcc.yml
- .github/workflows/testing-macos.yml
- src/CMakeLists.txt
- src/acc/hip/acc_hip.h
- tools/docker/lsan.supp
- cmake: add missing cuda library
- gha: drop mpich testing on macOS for now
- acc/hip: fix hipblas include
- docker: add another lsan suppresion for gcc-13
> Bugfixes for building DBCSR on macOS, with CUDA, latest-gcc

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/opencl/acc_opencl.h
> ocl: ensure compatibility with LIBXSMM 2.0

- CMakeLists.txt
- src/CMakeLists.txt
trivial change needed when the shared version of libcp2k is needed. OFF by default
> Add the posibility to build dbcsr shared library

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/Makefile
* Avoid specifying C-standard (and rely on compiler's default).
> ocl: updated Makefile

- CMakeLists.txt
- docs/guide/3-developer-guide/3-programming/1-overview/index.md
- src/CMakeLists.txt
- src/mpi/dbcsr_mpiwrap.F
The MPI 3.0 standard introduces the mpi_f08 module. This solves most issues arising with the old Fortran module (strong typing, non-blocking communication, allocation of memory, etc.). This PR enables this feature within DBCSR.
Because of experiences with its implementation in CP2K, its use must be explicitly requested by the user by adding the flag `-DUSE_MPI_F08=<ON|OFF>` while calling CMake. It is known that this feature requires more recent compilers (GCC version>10 or Intel compiler) and suitable MPI implementations (OpenMPI and IntelMPI seem to work well, MPICH has issues with Gfortran 11/12). Some of the admins should add or adjust a suitable test for this feature, as this is apparently not possible for me.
> Add support for the new mpi_f08 module

- src/acc/dbcsr_acc_devmem.F
- src/acc/dbcsr_acc_event.F
- src/acc/dbcsr_acc_hostmem.F
- src/acc/dbcsr_acc_stream.F
I've had for a while the problem that some CP2K regtests would fail with `cudaErrorInvalidResourceHandle` when I ran on two GPUs. I believe this is because the active device gets changed between calls to DBCSR.
Presumably, most users are not affect by this because Slurm et al. set `CUDA_VISIBLE_DEVICES` to pin GPUs to CPU sockets.
> acc: Always set active device before accessing a GPU

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
* Adjusted XHINTS for revised UMD.
* Makefile: Avoid hard-coded "lib64".
* Makefile: Support GNU=1.
* LIBXSMM upd. (Daint-CI).
> ocl: improved stand-alone reproducers and updated some settings

- docs/guide/2-user-guide/4-gpu/index.md
- docs/guide/3-developer-guide/2-documentation/index.md
- docs/guide/3-developer-guide/3-programming/2-accelerator-backend/2-libsmm_acc/index.md
- docs/guide/3-developer-guide/3-programming/2-accelerator-backend/3-libsmm_ocl/1-autotune.md
- docs/guide/3-developer-guide/3-programming/2-accelerator-backend/3-libsmm_ocl/2-bulktune.md
- docs/guide/3-developer-guide/3-programming/2-accelerator-backend/3-libsmm_ocl/index.md
- docs/guide/3-developer-guide/3-programming/2-accelerator-backend/3-opencl-backend.md
- docs/guide/3-developer-guide/3-programming/2-accelerator-backend/4-opencl-libsmm.md
- src/acc/README.md
- src/acc/opencl/README.md
- src/acc/opencl/smm/README-autotune.md
- src/acc/opencl/smm/README-bulktune.md
- src/acc/opencl/smm/README.md
* Structured OpenCL backend/libsmm to match CUDA/HIP documentation.
* Split folder specific documentation into separate READMEs.
* Introduction paragraph in User Guide's GPU section.
* Reduced overly structured documentation (sections).
> Revised documentation

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/opencl_libsmm.c
* Split device name among certain separators (cleanup)
- AMD Mi-GPUs expose OpenCL device names like "gfx90a:sramecc+:xnack-"
denoting certain machine states (ECC, UMA, etc).
- Use part(s) of device name which should map to parameters.
* Revised custom device split
> ocl: device name cleanup, revised/custom split into sub-devices

- src/acc/README.md
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/opencl_libsmm.h
* GCN: Rely on builtin atomics (Mi-GPUs); TODO: tuned params and check if supported.
* Allow relying on platform name instead of device name (c_dbcsr_acc_opencl_device_vendor).
* Introduced optional kernel-flags (opencl_libsmm_smm_t); needs some followup work later.
* Improved kernel by relying on work_group_broadcast in general.
* improved documentation for CUDA/OpenCL stand-alone drivers
* Modernized Shell script (acc_opencl.sh).
* Improved some runtime error messages.
* Some more debug/developer settings.
> ocl: GCN atomics for Mi-GPUs and other improvements

- src/acc/acc_bench_smm.c
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
* Removed support for sharing streams among threads, removed support for flush-bits.
* OPENCL_LIBSMM_VALIDATE_SMM: rely on libxsmm_matdiff_epsilon.
* Revised console output (acc_bench_smm).
> ocl: removed unused code

- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
* Allow filtering values written back to global memory (debug).
* Introduced constant minibatch-size (-DBSC).
* Refined/revised loop-unroll (BSC).
> ocl: leverage constant minibatch-size

- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
* tune_multiply.py
- Save good intermediate results after an earlier kernel failed.
- Fixed potential type-conversion error.
- Improved error message.
* SMM-kernel
- Repurposed 1<LU, and improved code-path using general blocks.
- Folded some explicit control-flow into loop-condition.
- Use 32-bit integer variables consistently.
- Removed superfluous casts.
- Improved comments.
> ocl: fixes and improvements

- src/acc/opencl/smm/tune_multiply.py
* Backup dotfile if it exists stemming from an earlier session.
* Adjusted default DB-location for OpenTuner.
> ocl: improved tuning script

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/acc_opencl.c
- Handle legacy-NEO and redirect NEO_CACHE_DIR to temporary folder.
- Introduced ACC_OPENCL_TEMPDIR.
- Updated LIBXSMM (Daint-CI).
> ocl: revised ACC_OPENCL_CACHE

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.sh
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/common/opencl_atomics.h
- src/acc/opencl/common/opencl_common.h
- src/acc/opencl/smm/kernels/multiply.cl
* Fixed incorrect type-cast (OPENCL_LIBSMM_SMM_KERNEL).
* Fixed c_dbcsr_acc_dev_mem_deallocate (svm_interop).
* Fixed warnings about unused variable (SMM-kernel).
* Inline include files (acc_opencl.sh).
> ocl: moved common code into separate OpenCL/header files

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/CMakeLists.txt
* Adjusted ACC_OPENCL_HANDLES_MAXCOUNT and ACC_OPENCL_STREAMS_MAXCOUNT.
* Avoid overhead of supporting ACC_OPENCL_STREAM_NULL.
* Introduced ACC_OPENCL_STREAM_COMPACT.
* Removed stream statistics.
> ocl: avoid overhead/regression and code-cleanup

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/common/opencl_atomics.h
- src/acc/opencl/common/opencl_common.h
- src/acc/opencl/smm/README.md
- src/acc/opencl/smm/opencl_libsmm.c
* Introduced element-size to allow better pointer-identification (c_dbcsr_acc_opencl_info_devptr).
* Not mentioning environment variable (renamed OPENCL_LIBSMM_SMM_ATOMICS->ACC_OPENCL_ATOMICS).
* Separated/modularized support for FP-atomics. Dropped cmpxchg2/xchg2 code-path.
* Cover more state in c_dbcsr_acc_opencl_device_t.
* Introduced c_dbcsr_acc_opencl_flags_atomics.
> ocl: separated/modularized support for FP-atomics

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
* Fixed case when ACC_OPENCL_MEM_DEVPTR is turned off at compile-time.
* Ensure termination message appears one time at most (cleanup).
* Introduced ACC_OPENCL_EVENT_CHAIN and ACC_OPENCL_EVENT_WAIT.
* Removed compile-time option for ACC_OPENCL_MEM_CPYSYNC.
* Removed compile-time setting (ACC_OPENCL_STREAM_NULL).
* Introduced WA-levels to distinct certain WAs.
* Ensure final cleanup (atexit).
> ocl: adjusted finalization-flow of OpenCL backend

- examples/dbcsr_example_3.cpp
- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/acc_libsmm.h
- src/acc/cuda_hip/calculate_norms.cpp
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/opencl_libsmm.c
- tests/dbcsr_test.cpp
* Calculate_norms: const-correctness to match Fortran wrapper's INTENT.
* OpenCL BE: Made ACC_OPENCL_WA flag-based (bit-wise toggles).
* OpenCL BE: Fixed macro order (acc_opencl.h).
* Eventually suppress "Fortran runtime warning:".
> Fixed interface for calculate_norms

- src/acc/cuda_hip/acc_dev.cpp
* Almost false positive aka incorrect warning.
* Shall be fixed regardless.
> Avoid unused const variable/verbose_print warning

- .ci/daint.cscs.ch/ocl.build.sh
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/tune_multiply.py
- src/acc/opencl/smm/tune_multiply.sh
* Account for initial flags (c_dbcsr_acc_opencl_flags_atomics).
* Improved support for multiple processes (auto-tune).
> ocl: fixed composing build flags and other improvements

- src/acc/opencl/acc_opencl.sh
* Remove include guards by default (simplistic).
* Fixed determining prefix.
* Avoid bulky symbols.
> ocl: improved script turning OpenCL code into resource/header

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
* Store cl_device_id in c_dbcsr_acc_opencl_device_t and rely on it (instead of querying it repeatedly).
* Make maximum size of work-group (WG) and preferred multiple available as part of device structure.
* Discover subgroups. Avoid some compile-time decision (OpenCL 3.0).
* Simplify handling WG-size (and SG-size).
* Code cleanup (_DEBUG).
> ocl: discover device properties once and simplified setting up WG-size

- src/acc/cuda_hip/acc_dev.cpp
* Citation: "Setting cudaLimitPrintfFifoSize must not be performed after launching any kernel that uses the printf() device system call - in such case cudaErrorInvalidValue will be returned."
* Since DeviceSetLimit is governed by ACC_API_CALL, the symbol NDEBUG must not be defined for reproducing the issue.
> Fixed #776

- src/acc/cuda_hip/acc_stream.cpp
- src/core/dbcsr_lib.F
* Avoid warning about format %p expecting void-pointer.
* Fixed typo (DBCSR_ABORT message).
> Fixed compilation warning and typo

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/smm/opencl_libsmm.c
* Adjusted an internal setting (ZEX_NUMBER_OF_CCS).
> ocl: demoted verbose messages to higher verbosity-level

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/kernels/multiply.cl
- src/acc/opencl/smm/tune_multiply.py
* Avoid potential segfault during finalization (ACC_OPENCL_DEVICE != 0).
* Avoid initializing private memory (aka registers) using curly braces.
* Lock ACC_OPENCL_NCCS behind first WA-bit (ZEX_NUMBER_OF_CCS).
* Improved error output (tune_multiply.py).
* Fixed ACC_OPENCL_ACTIVATE.
* Fixed comment.
> ocl: several minor fixes

- cmake/CompilerConfiguration.cmake
For instance, https://github.com/cp2k/dbcsr/actions/runs/9078189846/job/24944690222
> Avoid false positive warnings turned into an error

- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
* Using the CUDA backend, ACC_OPENCL_VERBOSE is not available.
* Prints the activated device and number of found devices.
* Helps, e.g., CI to capture basic information.
> ocl: always print number of devices found

- src/core/dbcsr_config.F
- src/core/dbcsr_lib.F
- src/mm/dbcsr_mm.F
- src/mm/dbcsr_mm_3d.F
- src/mm/dbcsr_mm_cannon.F
- src/mm/dbcsr_mm_hostdrv.F
- src/mm/dbcsr_mm_sched.F
This PR allows turning off DBCSR GPU acceleration at initialization, even if the library is compiled with the `-D__DBCSR_ACC` flag. This can be done by setting the environment variable `DBCSR_TURN_OFF_ACC=1`, or by passing a logical to the `dbcsr_set_config` subroutine (this will be useful for a future CP2K keyword).
Most changes take place in the `dbcsr_config.F` file. There, a new function called `use_acc()` is defined. It returns a logical, and replaces the `has_acc` variable used in the rest of the code.
The PR was validated by successfully running the CP2K regtests on a GPU machine, with and without the `DBCSR_TURN_OFF_ACC=1` environment variable.
Generally, the ability of turning off GPU acceleration at runtime should help with debugging, and with edge cases where DBCSR ACC …
> Allow tunring off DBCSR ACC with env variable

- tests/CMakeLists.txt
This property will allow to properly parallelize `ctest -j` calls
> Add CMake `PROCESSORS` properties

- src/acc/opencl/smm/opencl_libsmm.c
- src/acc/opencl/smm/tune_multiply.py
* Fixed constructing tuner instance.
* Simplified hard-coded rules.
> ocl: rely on default parameters more consistently

- examples/CMakeLists.txt
Avoid missing MPI symbols on HPE Cray systems for C++ applications
> Use FTN for linking

- src/acc/acc_bench_smm.c
- src/acc/acc_bench_trans.c
- src/acc/opencl/acc_opencl.c
* Apply rank-aware device-id only if ACC_OPENCL_ACTIVATE is defined.
* Forward error code and cleanup (c_dbcsr_acc_set_active_device).
* More sensible output in case of upfront error.
* Made selecting device rank-aware. Cleanup.
> ocl: minor corrections

- .pre-commit-config.yaml
- src/acc/libsmm_acc/kernels/smm_acc_dnt_medium.h
- src/acc/libsmm_acc/kernels/smm_acc_dnt_small.h
- src/acc/opencl/smm/opencl_libsmm.c
- clang-format is not stable version-to-version
- Hook is reformatting code already committed,  
it may be better to only change touched code
> Specify version of Clang-format

- src/acc/acc_libsmm.h
- src/acc/cuda/Makefile
- src/acc/opencl/Makefile
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_mem.c
- Fixed warning about referring a string-constant in non-constant way.
- Fixed warning about dropping cast qualifiers.
- Updated Makefile to support more warnings.
> ocl: fixed compilation warnings

- src/acc/dbcsr_acc_device.F
- src/data/dbcsr_ptr_util.F
- src/mpi/dbcsr_mpiwrap.F
- src/ops/dbcsr_operations.F
- Avoid nested parallelism (dbcsr_acc_set_active_device).
- Rely on omp_get_level (instead of omp_in_parallel),
omp_in_parallel only accounts for active regions.
- Avoid IF-condition as part of the WORKSHARE-directive.
- Removed WORKSHARE construct from dbcsr_ptr_util,
- otherwise keep WORKSHARE if not in parallel region.
- There is potentially invalid nesting (parallel+X),
e.g., nested in master or sections constructs.
> #857: Remove PARALLEL WORKSHARE

- src/acc/hip/acc_hip.cpp
- src/acc/hip/acc_hip.h
- Apparently, some API elements are "mirrored" (TODO: confirm why necessary).
- In particular, "hipHostAllocDefault" now changed "upstream" hence clash.
- Cleanup: removed duplicated prototype (hipHostAlloc).
> HIP: removed unused hipHostAllocDefault

- src/acc/opencl/acc_opencl.c
- c_dbcsr_acc_set_active_device triggers c_dbcsr_acc_init.
- DBCSR's ACC/OpenCL may also act as CP2K/offload library.
> ocl: lazy initialization

- CMakeLists.txt
- src/CMakeLists.txt
- Requesting LIBXSMM uses PkgConfig, which tests and resolves it.
- Hence: run this test prior instead of concluding with BLAS.
- BLAS is needed always and "auto" is no significant burden.
> CMake: allow USE_SMM=auto

- .gitignore
- .packit.yaml
- tools/fedora/dbcsr.spec
This adds packaging CI/CD for Fedora:
- When a new release is pushed, a pull-request is created at https://src.fedoraproject.org/rpms/dbcsr
- For each PR/commit to `develop`, the packaging is tested in copr
- (not yet implemented) Tests for packaging imports, e.g. via `find_package`. Needs some refactoring similar to [spglib](https://github.com/spglib/spglib)
To fully work the [packit app](https://packit.dev/docs/guide) needs to be installed on the repo. In the meantime the example run can be seen on my fork: https://github.com/LecrisUT/dbcsr/pull/1
soft-depends-on: #757
> feat: Fedora packaging

- src/acc/acc_bench.c
- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/smm/opencl_libsmm.c
- Improved/centralized applying debug flag.
- Removed internal options/flags.
- Reworked building kernels.
- acc_benc: revised handling NREPEAT_H2D.
- acc_benc: print correct size/timing.
> ocl: revised handling flags and build options

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- More detailed profile (c_dbcsr_acc_device_synchronize).
- Denote function name prefix-offset (profile).
- Enable ACC_OPENCL_PROFILE_DBCSR at compile-time.
- Runtime-control ACC_OPENCL_PROFILE.
- Removed ACC_OPENCL_PROFILE_TRANSFER.
> ocl: runtime-enable printing in DBCSR profile

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl.h
- src/acc/opencl/acc_opencl_event.c
- src/acc/opencl/acc_opencl_mem.c
- src/acc/opencl/acc_opencl_stream.c
- src/acc/opencl/smm/opencl_libsmm.c
- Ensure level-2 profile only for external transfers.
- API: introduced c_dbcsr_acc_opencl_hist.
- Simplified pool allocation (API).
- Cleaned-up initialization.
> ocl: histogram for profiling performance

- src/acc/opencl/acc_opencl.c
- src/acc/opencl/acc_opencl_mem.c
- Extended ACC_OPENCL_ASYNC flag to remaining memory-ops.
- Avoid creating certain events unnecessarily.
- Increased lock-scope.
- Adjusted debug.
- Code cleanup.
> ocl: fixed handling events wrt release/retain
