src/acc/libsmm_acc/libcusmm/libcusmm.cpp, src/acc/libsmm_acc/libcusmm/libcusmm_benchmark.cu, src/acc/libsmm_acc/libcusmm/libcusmm_benchmark.h, src/acc/libsmm_acc/libcusmm/tune.py, tests/Makefile.inc, tests/libcusmm_timer_multiply.cu, tests/libcusmm_unittest_multiply.cu, tests/libcusmm_unittest_transpose.cu
- add timer in tests/libcusmm_timer_multiply.cu
- add enum 'mode' in benchmarking. Values:
- test: for unit testing and jit-ed kernel validation
- tune: for kernel autotuning
- timing: for timing
=> libcusmm/tests: add timer

CMakeLists.txt
fixes https://github.com/cp2k/dbcsr/issues/49
=> cmake: fix build on macOS

tools/build_utils/check_archives.py
@shoshijak that should take care of the py3 compatibility with `check_archives.py`
=> tools/build_utils: make check_archives py3 compatible

Makefile.inc
Improved Makefile.inc (without the goal to make it sophisticated). Though, the CMake based build system is likely where sophistication goes into.
=> Improved Makefile.inc

.travis.yml
This enables new code relying on v1.10 (tests).
=> Updated to LIBXSMM 1.10.

src/acc/libsmm_acc/libcusmm/kernels/cusmm_dnt_helper.py, src/acc/libsmm_acc/libcusmm/kernels/cusmm_dnt_largeDB1.py, src/acc/libsmm_acc/libcusmm/kernels/cusmm_dnt_largeDB2.py, src/acc/libsmm_acc/libcusmm/kernels/cusmm_dnt_medium.py, src/acc/libsmm_acc/libcusmm/kernels/cusmm_dnt_small.py, src/acc/libsmm_acc/libcusmm/kernels/cusmm_dnt_tiny.py, src/acc/libsmm_acc/libcusmm/tune.py
This PR is a little minimalistic, as I will soon submit a larger PR touching autotuning and `libcusmm` kernel parameters.
=> Fix/autotuning: fixes to autotuning procedure

tests/Makefile.inc, tests/dbcsr_unittest3.F
Add a matrix-matrix multiplication test which features block-sizes commonly used in libcusmm.
Closes issue #131 
Sample of test output: 
```
-------------------------------------------------------------------------------
-                                                                             -
-                                DBCSR STATISTICS                             -
-                                                                             -
-------------------------------------------------------------------------------
COUNTER                                    TOTAL       BLAS       SMM       ACC
flops    13 x     4 x     4             59938944      74.0%      0.0%     26.0%
flops     4 x    13 x     4             60162752      74.3%      0.0%     25.7%
flops     4 x …
```
=> tests: add dbcsr_unittest3 to test libcusmm-backend

.pre-commit-config.yaml, .pre-commit/check_header.py, .travis.yml, Makefile, README.md, src/acc/libsmm_acc/libcusmm/README.md, src/acc/libsmm_acc/libcusmm/kernels/cusmm_dnt_base.py, src/acc/libsmm_acc/libcusmm/libcusmm_benchmark.cu, src/acc/libsmm_acc/libcusmm/predict_collect.py, src/acc/libsmm_acc/libcusmm/predict_evaluate.py, src/acc/libsmm_acc/libcusmm/tune_collect.py, src/acc/libsmm_acc/libcusmm/tune_merge.py, src/acc/libsmm_acc/libcusmm/tune_setup.py, src/acc/libsmm_acc/libcusmm/tune_submit.py, tests/generate_libcusmm_timer_multiply.py, tests/generate_libcusmm_unittest_multiply.py
Fixes minor issues, aesthetic details and documentation in scripts related to autotuning and collecting data.
=> libcusmm-autotune: small fixes

.ci/daint.cscs.ch/Jenkinsfile, .ci/daint.cscs.ch/build.sh, .ci/daint.cscs.ch/test.sh, CMakeLists.txt, tests/CMakeLists.txt
fixes one part of #147 once properly hooked up
=> ci: initial configuration for Jenkins@CSCS

src/acc/libsmm_acc/libcusmm/CMakeLists.txt
=> cmake/libcusmm: fix building with OpenMP

CMakeLists.txt, README.md
... and add missing cmake options to README
=> [cmake] add support for mpifort, mpif77, mpif90

src/tensors/dbcsr_tensor.F, src/tensors/dbcsr_tensor_block.F, src/tensors/dbcsr_tensor_split.F, src/tensors/dbcsr_tensor_test.F, tests/dbcsr_tensor_unittest.F
This generalizes the arguments of dbcsr_multiply first_row, first_column,
last_row, last_column, first_k, last_k to tensor contraction
=> Contraction of sub-tensors

src/tensors/dbcsr_tensor.F
This changes the tensor API and a pull request to CP2K will follow soon.
=> Generalize dbcsr_t_need_contract to subtensor contraction

src/block/dbcsr_block_operations.f90
Resolved warnings about "A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value".
=> INTENT(OUT) is not given an explicit value

src/tas/dbcsr_tas_base.F, src/tas/dbcsr_tas_mm.F, src/tensors/PACKAGE, src/tensors/dbcsr_tensor.F, src/tensors/dbcsr_tensor_api.F, src/tensors/dbcsr_tensor_block.F
* Tensor API is now compatible with symmetric DBCSR matrices
* DBCSR matrices are desymmetrized at conversion to tensors
=> Tensors: interface with symmetric matrices

src/tensors/dbcsr_tensor.F, src/tensors/dbcsr_tensor_block.F
Commit 5a3d57a715364a6a1f965da024c48236ec52ac91 broke tensor-matrix
interface for non-symmetric matrices
=> Tensors: fix related to symmetric matrices

cmake/CompilerConfiguration.cmake
I am not completely certain about this PR, but perhaps good enough.
=> Issue #261: apply -hnoacc flag

.gitignore, src/acc/libsmm_acc/.gitignore, src/acc/libsmm_acc/notebooks/inspect_training_data.ipynb, src/acc/libsmm_acc/notebooks/libsmm_acc_parameters_and_memory.png, src/acc/libsmm_acc/notebooks/libsmm_acc_predictive_modeling_features.png, tests/.gitignore
=> Update .gitignore after AMD port

src/mm/dbcsr_mm.F, src/tas/dbcsr_tas_base.F, src/tas/dbcsr_tas_mm.F, src/tas/dbcsr_tas_split.F, src/tas/dbcsr_tas_types.F, src/tensors/dbcsr_allocate_wrap.F, src/tensors/dbcsr_tensor.F, src/tensors/dbcsr_tensor_api.F, src/tensors/dbcsr_tensor_split.F, src/tensors/dbcsr_tensor_test.F, src/tensors/dbcsr_tensor_types.F, tests/CMakeLists.txt, tests/dbcsr_tensor_unittest.F
- API improvements
- avoid unnecessary communications
=> Minor improvements for tensors

src/block/dbcsr_block_access.f90, src/tas/dbcsr_tas_base.F, src/tas/dbcsr_tas_split.F, src/tas/dbcsr_tas_types.F, src/tensors/dbcsr_allocate_wrap.F, src/tensors/dbcsr_tensor.F, src/tensors/dbcsr_tensor.fypp, src/tensors/dbcsr_tensor_block.F, src/tensors/dbcsr_tensor_index.F, src/tensors/dbcsr_tensor_reshape.F, src/tensors/dbcsr_tensor_split.F, src/tensors/dbcsr_tensor_test.F, src/tensors/dbcsr_tensor_types.F
This pull request reduces the overhead of local block and index operations that made `dbcsr_t_copy` inefficient for small blocks.
=> Optimize tensor block and index operations

src/acc/acc_stream.cpp, src/acc/cuda/dbcsr_cuda_nvtx_cu.cu
=> fix compilation of macro __CUDA_PROFILING

examples/CMakeLists.txt, examples/dbcsr_tensor_example.F, src/tensors/dbcsr_tensor.F, src/tensors/dbcsr_tensor_types.F
This demonstrates how to use the tensor API and documents most of its
features
resolves #175
=> Tensor example

src/acc/PACKAGE, src/acc/cuda/PACKAGE, src/acc/hip/PACKAGE, src/acc/libsmm_acc/PACKAGE
Fixed PACKAGE references/dependencies to ACC interface (on top of PR #364).
=> fixed PACKAGE references

src/acc/PACKAGE, src/core/dbcsr_config.F, src/data/dbcsr_data_methods.F, src/data/dbcsr_data_methods_low.F, src/ops/dbcsr_operations.F, src/tas/dbcsr_tas_base.F, src/tas/dbcsr_tas_mm.F, src/tas/dbcsr_tas_reshape_ops.F, src/tas/dbcsr_tas_split.F, src/tas/dbcsr_tas_types.F, src/tensors/dbcsr_tensor.F, src/tensors/dbcsr_tensor_split.F, src/tensors/dbcsr_tensor_types.F
The parallel layout of tensors is adapted during the course of a batched
contraction in order to ensure best performance independent
of initial layout.
Adjust parameters for TAS multiplication algorithm to minimize
communication volume in DBCSR and TAS. Introduce new config option
'tas_split_factor'.
=> Tensors: Optimizations

src/mm/dbcsr_mm.F
=> Force thread_dist for C and left matrix to be the same

.ci/daint.cscs.ch/ocl.build.sh, src/acc/opencl/smm/tune_multiply.py
* SmmTuner object has no attribute 'device'.
* SmmTuner object has no attribute 'typename'
=> ocl-py: avoid attribute errors

.pre-commit-config.yaml, CMakeLists.txt, src/CMakeLists.txt, src/acc/hip/dbcsr_hip_profiling.F, src/core/PACKAGE, src/core/dbcsr_timings.F
=> Add HIP Profiling support

.ci/daint.cscs.ch/ocl.build.sh, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/tune_multiply.py
* Kernel code changes are micro-adjustments and manual/minor code optimization.
* Allow to tune only a selected subset of parameters.
=> ocl: more modular kernel

src/acc/opencl/README.md, src/acc/opencl/smm/README.md, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/tune_multiply.py
* Documented ACC_OPENCL_DUMP. Cleaned-up minor spelling issues.
* Revised/simplified default parameter configuration.
* Fixed updating JSONs if device name is given.
* Fixed taking environment variables.
=> ocl: fixed performance regression of untuned/default kernels

src/acc/opencl/Makefile, src/acc/opencl/README.md, src/acc/opencl/smm/README.md, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c
* Makefile: Take build dependency into account (tuned parameters).
=> ocl: documented tunable parameters and updated documentation

src/tas/dbcsr_tas_mm.F
=> Fix TAS distribution error

src/acc/opencl/acc_opencl.h, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/opencl_libsmm.h, src/acc/opencl/smm/tune_multiply.py
* Introduced TB and TC, adjusted tuning-levels.
* Disabled ACC_OPENCL_OVERMALLOC (not in use ATM).
* Disabled SP-kernels in DBCSR/production.
* Enabled ACC_OPENCL_THREADLOCAL_CONTEXT.
=> ocl: some additional tuning parameters

src/acc/opencl/acc_opencl.c
* Account for calling c_dbcsr_acc_init inside of parallel region (OpenMP).
* Improved verbose termination message.
* Sanitize TID.
=> ocl: improved discovering nthreads

src/acc/opencl/acc_opencl.c, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c
* Code-path WG=-1 (not yet reachable by auto-tuner) applies intel_reqd_sub_group_size (if possible).
* Code-path w/ sub_group_broadcast not yet reachable by auto-tuner (WG=-1 BK=1 AA=0).
* Avoid duplicating extensions requests (OPENCL_LIBSMM_SMM_KERNEL).
* Fixed/removed duplicating B-copy (registers).
* Improved generated code-format.
=> ocl: kernel variant using sub_group_broadcast

src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl_stream.c, src/acc/opencl/smm/opencl_libsmm.c
* Fixed the exposed number of devices and the selected device (ACC_OPENCL_DEVICE).
* Revised device exposure (order of applying rules).
* Improved/revised trace/debug information.
* Fixed considering stream priority.
=> ocl: revised and fixed device enumeration

src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl_stream.c
* Revised default (ACC_OPENCL_ASYNC).
=> ocl: refactored stream-priorities and revised some default

src/acc/acc_bench_smm.c, src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl_event.c, src/acc/opencl/acc_opencl_mem.c, src/acc/opencl/acc_opencl_stream.c, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/opencl_libsmm.h
* Introduced debug output/warning for queuing work from foreign thread.
* Extended SMM_BATCHSIZE to allows carrying number of repetitions.
* Fixed potential issue with asynchronously filling buffers.
=> ocl: improved handling errors, some code revision and cleanup

src/acc/opencl/smm/tune_multiply.py
=> ocl: fixed script for auto-tuning kernels

src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl_stream.c
* Interface cosmetics (internal).
* Fixed ACC_OPENCL_SHARE.
=> ocl: fixed verbose mode statistics

src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl_event.c, src/acc/opencl/acc_opencl_mem.c, src/acc/opencl/acc_opencl_stream.c, src/acc/opencl/smm/opencl_libsmm.c
* Fixed evil style after applying clang-format.
* Fixed pruning the number of devices.
=> ocl: pooled malloc for data-handles

src/block/dbcsr_block_operations.F, src/core/dbcsr_config.F, src/dist/dbcsr_dist_util.F, src/mpi/dbcsr_mpiwrap.F
Reset files to 9da56ebcf44ceefded994a590fc688f026cc8e92 (accidentally changed with #560 and not reverted in #561).
=> Reset accidentally changed files

src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl_stream.c
* Perform basic initialization even if ACC_OPENCL_DISABLE or no GPU found
* ACC_OPENCL_DISABLE: DBCSR does not support GPU-build but GPU found
=> ocl: improved initialization if no accelerator is found

.ci/daint.cscs.ch/ocl.build.sh, src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl_stream.c
* Fixed some remaining clang-format issues.
=> ocl: fixed pruning for homogeneous set of devices

src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c
* Additional control for atomic prototypes.
* Raised minimum/default WG-size.
=> ocl: adjusted runtime setup

.ci/daint.cscs.ch/ocl.build.sh, src/acc/acc_bench_smm.c, src/acc/opencl/smm/opencl_libsmm.c
* Issue prototype functions in any case. Code cleanup.
* Support randomized batch-size.
=> ocl: improved benchmark driver

src/acc/libsmm_acc/libsmm_acc_init.cpp
* Protect against multiple initialization.
* Protect against change of thread-count.
=> cuda/hip: improved initialization of libsmm_acc

src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl_stream.c, src/acc/opencl/smm/opencl_libsmm.c
* Increased locked region to cover not only kernel arguments/call. Fixed issue about recorded minibatch-size (kernel config).
* Experimental code-path (ACC_OPENCL_SHARE). Some more shortcuts and code cleanup (acc_opencl_stream.c).
* Fixed condition (scaling minibatch-size).
=> ocl: fixed condition

.clang-format, src/acc/cuda/Makefile, src/acc/libsmm_acc/generate_parameters.py, src/acc/opencl/Makefile, src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl_event.c, src/acc/opencl/acc_opencl_stream.c, src/acc/opencl/smm/opencl_libsmm.c
Other: allow to experiment with untuned/default parameters
* Accept to specify a generic GPU (CUDA/HIP).
=> Adjusted Clang format

src/acc/acc_bench_smm.c, src/acc/libsmm_acc/libsmm_acc_init.cpp, tests/CMakeLists.txt
* Fixed warning about unused variable.
=> Build acc_bench drivers as part of the tests

src/acc/acc_bench_smm.c, src/acc/acc_bench_trans.c, src/acc/libsmm_acc/libsmm_acc_init.cpp, tests/dbcsr_acc_test.c
* See https://github.com/cp2k/dbcsr/commit/a2bedce43c925591ac1de64da9e044897ae8b61d#commitcomment-69423044
=> Provide ACC timer stubs for non-ACC compilation

.ci/daint.cscs.ch/ocl.build.sh, src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl.sh, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/opencl_libsmm.h, src/acc/opencl/smm/tune_multiply.py
* Load new embedded parameter format (multiple devices).
* Parse custom/override ACC_OPENCL_DEVMATCH.
* Fixed regular expression (tune_multiply.py).
* Relaxed c_dbcsr_acc_opencl_devuid.
=> ocl: embed and load parameters for multiple/different devices

src/acc/opencl/README.md, src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl_event.c, src/acc/opencl/acc_opencl_mem.c, src/acc/opencl/acc_opencl_stream.c, src/acc/opencl/smm/README.md, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c
* Updated documentation.
* Removed UNROLL_INNER.
=> ocl: removed code related to ACC_OPENCL_DEBUG

src/acc/opencl/acc_opencl.c
* Avoid potential compiler warning (OpenCL prior to 1.2).
=> ocl: allow to split devices equally

src/acc/opencl/Makefile, src/acc/opencl/acc_opencl_mem.c, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c
* Improved reliability, and issue performance warning (synchronous d2h).
* Improved detecting OpenCL ICD-loader (Makefile).
* More control of forcing atomics.
=> ocl: improved platform coverage

.ci/daint.cscs.ch/ocl.build.sh, src/acc/acc_bench_smm.c, src/acc/cuda/Makefile, src/acc/opencl/acc_opencl.c, src/acc/opencl/smm/opencl_libsmm.c
* Anticipate PR #629 (Makefile/standalone)
* Removed incorrect prototypes.
* Avoid compilation warning.
=> ocl: minor fixes, prepare for #629

src/core/dbcsr_config.F, src/data/dbcsr_ptr_util.F, src/dist/dbcsr_dist_methods.F, src/mm/dbcsr_mm.F, src/mm/dbcsr_mm_3d.F, src/mm/dbcsr_mm_accdrv.F, src/mm/dbcsr_mm_cannon.F, src/mm/dbcsr_mm_csr.F, src/mm/dbcsr_mm_hostdrv.F, src/mm/dbcsr_mm_multrec.F, src/utils/dbcsr_string_utilities.F
Introducing a machinery to set configuration parameters via env variables.
Currently, only some parameters (it will be extended to all) can now be set via env variables.
The priority of setting is:
- env
- user
- default
=> Use env variables for setting CFG

src/acc/opencl/smm/tune_multiply.sh
* Fixed exit condition when splitting work into parts.
* Always apply default duration unless CONTINUE.
=> ocl: fixed exit-condition of tuning script

src/acc/libsmm_acc/predict/README.md, src/acc/libsmm_acc/predict/predict_collect.py, src/acc/libsmm_acc/predict/predict_genpars.py, src/acc/libsmm_acc/predict/predict_helpers.py, src/acc/libsmm_acc/predict/prepare_training_data.py, src/acc/libsmm_acc/predict/requirements.txt, src/acc/libsmm_acc/tune/tune_collect.py, src/acc/libsmm_acc/tune/tune_merge.py, src/acc/libsmm_acc/tune/tune_setup.py
- 3043 autotuned A100 kernels
- 71048 predicted A100 kernels
=> Extend database of autotuned and predicted A100 kernels

.ci/daint.cscs.ch/ocl.build.sh, src/acc/opencl/smm/tune_multiply.sh
=> ocl: modernized script for bulk-tuning kernels

src/acc/opencl/acc_opencl.c
* Fixed parsing list of allowed device.
* Adjusted execution environment.
=> ocl: fixed parsing list of allowed device

src/acc/opencl/acc_opencl.c, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/tune_multiply.py
* Split into maximum number of sub-devices if ACC_OPENCL_DEVSPLIT=1
- If 1<ACC_OPENCL_DEVSPLIT always split according to CL_DEVICE_PARTITION_EQUALLY.
- Prioritize CL_DEVICE_AFFINITY_DOMAIN_NUMA if ACC_OPENCL_DEVSPLIT=0|1.
* Experimental support for XF. Remove XF=0 when storing JSON.
- Handle extension flag (XF) with currently only one state-bit.
* Other improvements/changes
- Check finally tuned kernel even when handling signal (recursion).
- Adjusted built-in default (OPENCL_LIBSMM_SMM_AL).
=> ocl: revised device-split, additional tuning param, and other improvements

src/acc/opencl/smm/tune_multiply.py
* Ensure check-pointed parameters produce correct results
* Turn last correct checkpoint into final parameter set
=> ocl: improved tuner script

src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/tune_multiply.py
* tune_multiply.py: ensure correct type.
* tune_multiply.py: cleanup.
=> ocl: updated and improved OPENCL_LIBSMM_VALIDATE

src/acc/opencl/smm/opencl_libsmm.c
* Read-back parameter stack from device (rather than using host_param_stack).
* Cleanup.
=> ocl: fixed OPENCL_LIBSMM_VALIDATE_SMM

.ci/daint.cscs.ch/ocl.build.sh, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/tune_multiply.py
* tune_multiply.py
- Make OPENCL_LIBSMM_SMM_XF an integer upfront.
- Fixed/improved handling recursion (CTRL-C).
- Ensure normalized/sorted output.
- Properly implement interface.
- Improved handling errors. -Locked XF-property.
* Improved ensuring minimum requested WG-size.
* SMM-Kernel: keep and improved code comments.
=> ocl: improved tuning script

src/acc/opencl/acc_opencl.c, src/acc/opencl/smm/tune_multiply.py
* Control ZE_FLAT_DEVICE_HIERARCHY.
* Improved info output.
=> ocl: improved device setup

src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl.sh
* Account for __OFFLOAD_OPENCL (aliasing __OPENCL).
* Raised limit (ACC_OPENCL_STREAMS_MAXCOUNT).
* acc_opencl.sh
- Improved buffering file output (speedup generating header).
- Support generating banner (CP2K's format policy).
=> ocl: further prepared for CP2K's Offload/DBM/DBT libraries

src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/smm/opencl_libsmm.c
* Adjusted c_dbcsr_acc_opencl_flags_atomics.
* Code/interface comment.
=> ocl: adjusted internal interface

.ci/daint.cscs.ch/ocl.build.sh, src/acc/opencl/acc_opencl.c, src/mm/dbcsr_mm_hostdrv.F
* Unrelated: rely on debug_mod similar to careful_mod.
=> ocl: removed debug helper

.pre-commit/headers/c_cpp.3, src/acc/opencl/acc_opencl.c, src/acc/opencl/acc_opencl.h, src/acc/opencl/acc_opencl_event.c, src/acc/opencl/acc_opencl_mem.c, src/acc/opencl/acc_opencl_stream.c, src/acc/opencl/common/opencl_atomics.h, src/acc/opencl/common/opencl_common.h, src/acc/opencl/smm/kernels/multiply.cl, src/acc/opencl/smm/kernels/transpose.cl, src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/opencl_libsmm.h
* Harmonize with CP2K/offload interface/component.
=> ocl: changed license to BSD-3-Clause

src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/opencl_libsmm.h, src/acc/opencl/smm/tune_multiply.py
* Introduced re-validating parameters and an entire JSON-file collection.
* Allow to select kernel to rely on default/built-in parameters.
* Disable USM in case of OPENCL_LIBSMM_VALIDATE.
=> ocl: improved debug and script for tuning kernel parameters

src/tensors/dbcsr_array_list_methods.F, src/tensors/dbcsr_tensor_types.F
- Removed duplicated array_eq_i.
=> Implement array_eq_i using libxsmm_diff

src/acc/acc_bench.c, src/acc/opencl/acc_opencl.c, src/acc/opencl/smm/opencl_libsmm.c
- OpenCL: define NDEBUG for kernel-code as well.
=> ACC/bench: allow to check for performance baseline

src/acc/opencl/smm/tune_multiply.py
Removed detailed statistics for retain/delete lists. Revised retaining/deleting files (JSON database).
Fixed default-value of an optional argument.
Simplified handling retain/delete-lists.
Simplified handling nogflops argument.
Colored output, and code comments.
Further reduced code.
=> ocl: improved script for auto-tuning parameters

src/acc/opencl/smm/opencl_libsmm.c, src/acc/opencl/smm/tune_multiply.py
- Introduced OPENCL_LIBSMM_TODO.
- Adjusted quick-option.
=> ocl: final code cleanup

src/acc/opencl/acc_opencl_mem.c
- Always perform ACC_OPENCL_MEM_EVTRELEASE code-path.
- Removed ACC_OPENCL_MEM_EVTRELEASE definition.
=> ocl: more accurate profiling events
